/**
 * AUTO-GENERATED by dismantle-messagelist.cjs (spec ta2: steps).
 * Blocks moved verbatim from components/MessageList.tsx. Behavior unchanged.
 */
import {
	type ToolView,
} from '../groupTranscript';
import {
	categorize,
	lineRange,
	parseTodosFromInput,
	writeSettledVerb,
} from './todos';
import {ActivityStep, DiffStat, basename, countDiffHunks, estimateDiffFromArgs, parseJson, strField} from '../toolActivity';

export function toolToStep(tool: ToolView): ActivityStep {
	const obj = parseJson(tool.input);
	const path = strField(obj, 'file_path', 'filePath', 'path', 'target');
	const pattern = strField(obj, 'pattern', 'query', 'glob', 'glob_pattern');
	const command = strField(obj, 'command', 'cmd', 'text');
	const err = tool.status === 'error';
	// 仅真正在途时 shimmer — 有 result 表示已结束。
	const running = tool.status === 'running' && !tool.result?.trim();

	// Agent 子代理：与普通工具同一 activity 轨（Delegating / Delegated）。
	const toolNameLower = tool.name.toLowerCase();
	if (toolNameLower === 'agent') {
		const desc = strField(
			obj,
			'description',
			'desc',
			'prompt',
			'task',
			'subagent_type',
		);
		let detail = desc || 'sub-agent';
		if (detail.length > 72) {
			detail = `${detail.slice(0, 72)}…`;
		}
		return {
			id: tool.id,
			verb: running ? 'Delegating' : err ? 'Failed' : 'Delegated',
			detail,
			args: tool.input?.trim() ? tool.input : undefined,
			error: err,
			running,
			result: tool.result,
			agent: true,
		};
	}

	const cat = categorize(tool.name);
	const diff = tool.result ? countDiffHunks(tool.result) : undefined;
	const file = path ? basename(path) : '';
	// 42 号：后台任务三工具的 job_id（detail 锚定到具体任务）。
	const jobId = strField(obj, 'job_id', 'jobId');

	let verb = 'Ran';
	let detail = tool.name;

	// 43 号：Bash 被透明路由到专用工具时，结果头带 `[routed: Bash <cmd> → <Tool>]`。
	// 决策 5：仅在「显示所用工具」处展示 `Bash → <Tool>`，其他任何地方不标注。
	const routedTo = /^\[routed: Bash [^\u2192]+\u2192 (\w+)/.exec(tool.result ?? '')?.[1];

	switch (cat) {
		case 'write':
			verb = running
				? 'Writing'
				: err
					? 'Failed'
					: writeSettledVerb(tool.result);
			detail = file || path || tool.name;
			break;
		case 'edit':
			verb = running ? 'Editing' : err ? 'Failed' : 'Edited';
			detail = file || path || tool.name;
			break;
		case 'read':
			if (tool.name.toLowerCase() === 'screenshot') {
				verb = running ? 'Capturing' : 'Captured';
				detail = 'screen';
			} else if (tool.name.toLowerCase() === 'job_output') {
				verb = running ? 'Checking' : 'Checked';
				detail = jobId ? `job ${jobId}` : 'background job';
			} else if (tool.name.toLowerCase() === 'job_list') {
				verb = running ? 'Checking' : 'Checked';
				detail = 'background jobs';
			} else {
				verb = running ? 'Reading' : 'Read';
				detail = (file || path || tool.name) + lineRange(obj);
			}
			break;
		case 'search':
			if (
				tool.name.toLowerCase() === 'websearch' ||
				tool.name.toLowerCase().includes('web_search')
			) {
				verb = running ? 'Searching' : 'Searched';
				detail = pattern || tool.name;
			} else if (tool.name.toLowerCase().includes('glob')) {
				verb = running ? 'Globbing' : 'Globbed';
				detail = pattern || file || tool.name;
			} else {
				verb = running ? 'Grepping' : 'Grepped';
				// 管道/括号查询加引号，避免被看成「展开|收起」类 UI 残片
				const pat = pattern
					? /[|()]/.test(pattern)
						? `“${pattern}”`
						: pattern
					: '';
				detail = pat
					? file
						? `${pat} in ${file}`
						: pat
					: file || tool.name;
			}
			break;
		case 'todo': {
			verb = running ? 'Updating' : 'Checked';
			const todoCount = parseTodosFromInput(tool.input).length;
			detail =
				todoCount > 0
					? `${todoCount} task${todoCount === 1 ? '' : 's'}`
					: 'to-do list';
			break;
		}
		case 'lint':
			if (tool.name.toLowerCase().includes('diagnostics')) {
				verb = 'Diagnostics';
			} else {
				verb = running ? 'Linting' : 'Linted';
			}
			detail = file || path || tool.name;
			break;
		case 'run':
			verb = running ? 'Running' : 'Ran';
			if (tool.name.toLowerCase() === 'echo') {
				detail = command ? `echo ${command}` : 'echo';
			} else if (tool.name.toLowerCase() === 'gettime') {
				detail = 'getTime';
			} else if (tool.name.toLowerCase() === 'job_kill') {
				verb = running ? 'Stopping' : 'Stopped';
				detail = jobId ? `job ${jobId}` : 'background job';
			} else {
				detail = command || tool.name;
				if (detail.length > 72) {
					detail = `${detail.slice(0, 72)}…`;
				}
			}
			break;
		default:
			verb = running ? 'Calling' : 'Called';
			detail = file || pattern || command || tool.name;
	}

	const estimated =
		cat === 'edit' || cat === 'write'
			? (diff ?? estimateDiffFromArgs(tool.input))
			: undefined;

	if (routedTo && tool.name.toLowerCase() === 'bash') {
		detail = `Bash → ${routedTo}`;
	}

	return {
		id: tool.id,
		verb,
		detail,
		args: tool.input?.trim() ? tool.input : undefined,
		diff: estimated,
		error: err,
		running,
		result: tool.result,
	};
}

export function formatThoughtDetail(elapsedMs: number): string {
	if (elapsedMs < 3000) {
		return 'briefly';
	}
	return `${Math.round(elapsedMs / 1000)}s`;
}

/**
 * 根据 tool 的 reasoning 快照插入 Thought 行。
 * 仅在有真实 reasoning 内容时插入；不再用时间戳合成空 Thought（避免无序杂乱）。
 */
export function injectThoughtSteps(
	steps: ActivityStep[],
	tools: ToolView[],
): ActivityStep[] {
	if (tools.length === 0) {
		return steps;
	}
	const out: ActivityStep[] = [];
	for (let i = 0; i < tools.length; i += 1) {
		const tool = tools[i]!;
		const reasoning = tool.reasoningBefore?.trim();
		if (reasoning) {
			out.push({
				id: `thought-before-${tool.id}`,
				verb: 'Thought',
				detail: formatThoughtDetail(tool.thoughtMs ?? 0),
				thoughtContent: reasoning,
				running: false,
			});
		}
		out.push(steps[i]!);
	}
	return out;
}

/** 运行中思考阶段：末行追加或更新 live Thought 步骤。 */
export function appendLiveThoughtStep(
	steps: ActivityStep[],
	opts: {
		active: boolean;
		since: number | null;
		now?: number;
		content?: string;
	},
): ActivityStep[] {
	if (!opts.active || opts.since == null) {
		return steps;
	}
	if (steps.some(s => s.running && s.verb !== 'Thought')) {
		return steps;
	}
	const cleared = steps.map(s =>
		s.running ? {...s, running: false as const} : s,
	);
	const elapsed = (opts.now ?? Date.now()) - opts.since;
	const detail = formatThoughtDetail(elapsed);
	const thoughtContent = opts.content?.trim() || undefined;
	const last = cleared.at(-1);

	// 已有 live / stream Thought → 原地更新，禁止再叠一行 Thinking
	if (
		last &&
		last.verb === 'Thought' &&
		(last.id === 'thought-live' ||
			last.id.startsWith('thought-stream-') ||
			/^thought-.+-\d+$/.test(last.id))
	) {
		return [
			...cleared.slice(0, -1),
			{
				...last,
				detail,
				thoughtContent: thoughtContent || last.thoughtContent,
				running: true,
			},
		];
	}

	// 末行已是 settle 的 Thought（isThought / reasoning 快照）→ 升为 live，勿再插 Thinking
	if (last?.verb === 'Thought') {
		return [
			...cleared.slice(0, -1),
			{
				...last,
				detail,
				thoughtContent: thoughtContent || last.thoughtContent,
				running: true,
			},
		];
	}

	return [
		...cleared,
		{
			id: 'thought-live',
			verb: 'Thought',
			detail,
			thoughtContent,
			running: true,
		},
	];
}

/**
 * 保证 UI 层至多一个步骤带 running（当前在途步骤）。
 * 已完成步骤强制 running=false，避免整段 active 时全部 shimmer。
 */
export function normalizeActivitySteps(
	steps: ActivityStep[],
	active: boolean,
): ActivityStep[] {
	if (steps.length === 0) {
		return steps;
	}
	if (!active) {
		let settled = false;
		const out = steps.map(s => {
			if (!s.running) {
				return s;
			}
			settled = true;
			return {...s, running: false};
		});
		return settled ? out : steps;
	}
	const lastRunningIdx = steps.findLastIndex(s => s.running);
	if (lastRunningIdx < 0) {
		return steps;
	}
	let changed = false;
	const out = steps.map((s, i) => {
		const live = i === lastRunningIdx;
		if (Boolean(s.running) === live) {
			return s;
		}
		changed = true;
		return {...s, running: live};
	});
	return changed ? out : steps;
}

export function summarizeTools(tools: ToolView[]): {
	summary: string;
	diffs: DiffStat;
	steps: ActivityStep[];
} {
	const toolSteps = tools.map(toolToStep);
	const steps = injectThoughtSteps(toolSteps, tools);
	let createdFiles = 0;
	let wroteFiles = 0;
	let editFiles = 0;
	let readFiles = 0;
	let searches = 0;
	let commands = 0;
	let todos = 0;
	let add = 0;
	let del = 0;
	const seenCreated = new Set<string>();
	const seenWrote = new Set<string>();
	const seenEdit = new Set<string>();
	const seenRead = new Set<string>();

	for (let i = 0; i < tools.length; i += 1) {
		const t = tools[i]!;
		const step = toolSteps[i]!;
		const cat = categorize(t.name);
		if (step.diff) {
			add += step.diff.add;
			del += step.diff.del;
		}
		const key = step.detail || t.id;
		if (step.verb === 'Created' || step.verb === 'Creating') {
			if (!seenCreated.has(key)) {
				seenCreated.add(key);
				createdFiles += 1;
			}
		} else if (step.verb === 'Wrote' || step.verb === 'Writing') {
			if (!seenWrote.has(key)) {
				seenWrote.add(key);
				wroteFiles += 1;
			}
		} else if (cat === 'edit') {
			if (!seenEdit.has(key)) {
				seenEdit.add(key);
				editFiles += 1;
			}
		} else if (cat === 'read') {
			if (!seenRead.has(key)) {
				seenRead.add(key);
				readFiles += 1;
			}
		} else if (cat === 'search') {
			searches += 1;
		} else if (cat === 'todo') {
			todos += 1;
		} else {
			commands += 1;
		}
	}

	const parts: string[] = [];
	if (createdFiles > 0) {
		parts.push(
			`Created ${createdFiles} file${createdFiles === 1 ? '' : 's'}`,
		);
	}
	if (wroteFiles > 0) {
		parts.push(`Wrote ${wroteFiles} file${wroteFiles === 1 ? '' : 's'}`);
	}
	if (editFiles > 0) {
		parts.push(`Edited ${editFiles} file${editFiles === 1 ? '' : 's'}`);
	}
	if (readFiles > 0) {
		parts.push(`Read ${readFiles} file${readFiles === 1 ? '' : 's'}`);
	}
	if (searches > 0) {
		parts.push(`${searches} search${searches === 1 ? '' : 'es'}`);
	}
	if (commands > 0) {
		parts.push(`ran ${commands} command${commands === 1 ? '' : 's'}`);
	}
	if (todos > 0) {
		parts.push('updated to-dos');
	}
	if (parts.length === 0 && tools.length > 0) {
		parts.push(`Ran ${tools.length} tool${tools.length === 1 ? '' : 's'}`);
	}
	let summary = parts.join(', ');
	if (add > 0 || del > 0) {
		summary = summary ? `${summary} +${add} -${del}` : `+${add} -${del}`;
	}
	if (!summary) {
		summary = 'Working…';
	}
	return {summary, diffs: {add, del}, steps};
}

/**
 * 任务收尾时长：如「Worked for 7m 33s」。
 */
