/**
 * AUTO-GENERATED by dismantle-messagelist.cjs (spec ta1: todos).
 * 代码块自 components/MessageList.tsx 原样迁移，行为不变。
 */
import {
	parseJsonValue,
} from '../safeJson';
import {
	type ToolView,
	type TurnItem,
} from '../groupTranscript';
import {ActivityStep, ChangedFile, FILE_CHANGE_VERBS, basename, countDiffHunks, estimateDiffFromArgs, parseJson, strField, toolToStep} from '../toolActivity';

export function extractDiffFence(text: string): string | undefined {
	const m = text.match(/```diff\r?\n([\s\S]*?)```/i);
	const body = m?.[1]?.replace(/\s+$/, '');
	return body || undefined;
}

/** 聚合已编辑/写入文件供 Files Changed 卡片使用。 */
export function collectChangedFiles(steps: ActivityStep[]): ChangedFile[] {
	const map = new Map<string, ChangedFile>();
	for (const s of steps) {
		if (s.running || s.error) {
			continue;
		}
		if (!FILE_CHANGE_VERBS.has(s.verb)) {
			continue;
		}
		const obj = parseJson(s.args ?? '');
		const path =
			strField(obj, 'file_path', 'filePath', 'path', 'target') || s.detail;
		if (!path) {
			continue;
		}
		const name = basename(path);
		const key = path.replace(/\\/g, '/').toLowerCase();
		const fromResult = s.result ? countDiffHunks(s.result) : undefined;
		const fromArgs = estimateDiffFromArgs(s.args);
		const add = s.diff?.add ?? fromResult?.add ?? fromArgs?.add ?? 0;
		const del = s.diff?.del ?? fromResult?.del ?? fromArgs?.del ?? 0;
		const created = s.verb === 'Created';
		const diff = s.result ? extractDiffFence(s.result) : undefined;
		const prev = map.get(key);
		if (prev) {
			prev.add += add;
			prev.del += del;
			if (created) {
				prev.created = true;
			}
			// 优先最新的非空 diff 预览。
			if (diff) {
				prev.diff = diff;
			}
		} else {
			map.set(key, {
				path,
				name,
				add,
				del,
				...(created ? {created: true} : {}),
				...(diff ? {diff} : {}),
			});
		}
	}
	return [...map.values()];
}

/** 从整轮 tools 收集变更文件。 */
export function collectChangedFilesFromItems(items: TurnItem[]): ChangedFile[] {
	const steps: ActivityStep[] = [];
	for (const item of items) {
		if (item.kind === 'tool') {
			steps.push(toolToStep(item.tool));
		}
	}
	return collectChangedFiles(steps);
}

/** 多 Agent：把子任务 filesTouched 并入主会话 Changes（主 transcript 无 Write 工具行）。 */
export function mergeChangedFilesWithPaths(
	base: ChangedFile[],
	paths: string[] | undefined,
): ChangedFile[] {
	if (!paths?.length) {
		return base;
	}
	const map = new Map<string, ChangedFile>();
	for (const f of base) {
		map.set(f.path.replace(/\\/g, '/').toLowerCase(), {...f});
	}
	for (const raw of paths) {
		const path = String(raw || '').trim();
		if (!path) {
			continue;
		}
		const key = path.replace(/\\/g, '/').toLowerCase();
		if (map.has(key)) {
			continue;
		}
		map.set(key, {
			path,
			name: basename(path),
			add: 0,
			del: 0,
		});
	}
	return [...map.values()];
}


export type TodoStatus = 'pending' | 'in_progress' | 'completed';

export type TodoItemView = {
	content: string;
	status: TodoStatus;
	activeForm: string;
};

export type TodoSnapshot = {
	id: string;
	todos: TodoItemView[];
	running: boolean;
};

export const TODO_LIST_TAG_RE = /<todo_list>\s*([\s\S]*?)\s*<\/todo_list>/i;

export function isTodoToolName(name: string): boolean {
	return name.toLowerCase().includes('todo');
}

export function normalizeTodoRows(rawList: unknown): TodoItemView[] {
	if (!Array.isArray(rawList)) {
		return [];
	}
	const out: TodoItemView[] = [];
	for (const raw of rawList) {
		if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
			continue;
		}
		const row = raw as Record<string, unknown>;
		const content = typeof row.content === 'string' ? row.content.trim() : '';
		const status = row.status;
		const activeRaw =
			typeof row.activeForm === 'string'
				? row.activeForm.trim()
				: typeof row.active_form === 'string'
					? row.active_form.trim()
					: '';
		// activeForm 对 UI 可选 — 回退到 content 以便 dock 仍显示。
		const activeForm = activeRaw || content;
		if (
			!content ||
			(status !== 'pending' &&
				status !== 'in_progress' &&
				status !== 'completed')
		) {
			continue;
		}
		out.push({content, status, activeForm});
	}
	return out;
}

/** 将 TodoWrite tool input 解析为清单行。 */
export function parseTodosFromInput(input: string): TodoItemView[] {
	const obj = parseJson(input);
	if (!obj || !Array.isArray(obj.todos)) {
		return [];
	}
	return normalizeTodoRows(obj.todos);
}

/**
 * 从 TodoWrite tool_result 解析权威快照。
 * 标签缺失时返回 null（旧版结果 → 回退到 input）。
 * 标签存在但为空时返回 []（列表已清除 / 全部完成已存储）。
 */
export function parseTodosFromResult(result: string): TodoItemView[] | null {
	const m = TODO_LIST_TAG_RE.exec(result);
	if (!m) {
		return null;
	}
	const inner = m[1]?.trim() ?? '';
	if (!inner) {
		return [];
	}
	try {
		return normalizeTodoRows(parseJsonValue(inner) ?? []);
	} catch {
		return null;
	}
}

export function todoSnapshotFromTool(tool: ToolView): TodoSnapshot | null {
	if (!isTodoToolName(tool.name)) {
		return null;
	}
	const running = tool.status === 'running' && !tool.result?.trim();
	const fromResult = tool.result?.trim()
		? parseTodosFromResult(tool.result)
		: null;

	// tool settle 后优先 backend <todo_list>。
	if (fromResult !== null && !running) {
		return {id: tool.id, todos: fromResult, running: false};
	}

	const fromInput = parseTodosFromInput(tool.input);
	if (fromInput.length === 0) {
		// 通过 input 显式空替换，或 payload 不可用。
		if (Array.isArray(parseJson(tool.input)?.todos)) {
			return {id: tool.id, todos: [], running};
		}
		return null;
	}
	return {id: tool.id, todos: fromInput, running};
}

/** 单轮最新 TodoWrite 快照（全列表替换 → 后者胜出）。 */
export function collectLatestTodosFromItems(
	items: TurnItem[],
): TodoSnapshot | null {
	let latest: TodoSnapshot | null = null;
	for (const item of items) {
		if (item.kind !== 'tool') {
			continue;
		}
		const snap = todoSnapshotFromTool(item.tool);
		if (snap) {
			latest = snap;
		}
	}
	return latest;
}

/** 计划列表仍活跃时为 true：已创建且并非每项都已完成。 */
export function isLiveTodoSnapshot(
	snap: TodoSnapshot | null | undefined,
): snap is TodoSnapshot {
	if (!snap || snap.todos.length === 0) {
		return false;
	}
	return !snap.todos.every(t => t.status === 'completed');
}

/**
 * 输入框 dock 的 session 范围实时 todo 列表。
 * 生命周期：首个含项的 TodoWrite → 每项完成时隐藏
 * （或列表被清除）。完成行带勾选保持可见直到那时。
 */
export function collectLiveSessionTodos(
	items: TurnItem[],
): TodoSnapshot | null {
	const latest = collectLatestTodosFromItems(items);
	return isLiveTodoSnapshot(latest) ? latest : null;
}

export function isTodoActivityStep(step: ActivityStep): boolean {
	return step.verb === 'Updating' || step.verb === 'Checked';
}

/** activity 段中最后一个 TodoWrite 步骤的 Todo 快照。 */
export function collectLatestTodosFromSteps(
	steps: ActivityStep[],
): TodoSnapshot | null {
	let latest: TodoSnapshot | null = null;
	for (const step of steps) {
		if (!isTodoActivityStep(step)) {
			continue;
		}
		const todos = parseTodosFromInput(step.args ?? '');
		if (todos.length === 0) {
			continue;
		}
		latest = {
			id: step.id,
			todos,
			running: Boolean(step.running),
		};
	}
	return latest;
}

export function lineRange(obj: Record<string, unknown> | null): string {
	if (!obj) {
		return '';
	}
	const start = obj.start_line ?? obj.startLine ?? obj.offset;
	const end = obj.end_line ?? obj.endLine;
	const limit = obj.limit;
	if (typeof start === 'number' && typeof end === 'number') {
		return ` L${start}-${end}`;
	}
	if (typeof start === 'number' && typeof limit === 'number') {
		return ` L${start}-${start + limit}`;
	}
	if (typeof start === 'number') {
		return ` L${start}`;
	}
	return '';
}

export type ToolCat =
	| 'write'
	| 'edit'
	| 'read'
	| 'search'
	| 'run'
	| 'todo'
	| 'lint'
	| 'other';

export function categorize(name: string): ToolCat {
	const n = name.toLowerCase();
	// 42 号：后台任务三工具——output/list 只读卡；kill 执行卡。
	if (n === 'job_output' || n === 'job_list') {
		return 'read';
	}
	if (n === 'job_kill') {
		return 'run';
	}
	// Write 在 edit 之前 — "write" 不得折叠为 Edited。
	if (n.includes('write') && !n.includes('todo')) {
		return 'write';
	}
	if (n.includes('edit') || n.includes('notebook')) {
		return 'edit';
	}
	if (n.includes('lint') || n.includes('diagnostics')) {
		return 'lint';
	}
	if (n === 'git' || n.startsWith('git')) {
		return 'read';
	}
	if (
		n.includes('read') ||
		n === 'read' ||
		n.includes('explore') ||
		n === 'screenshot'
	) {
		return 'read';
	}
	if (
		n.includes('grep') ||
		n.includes('glob') ||
		n.includes('search') ||
		n === 'glep'
	) {
		return 'search';
	}
	if (n.includes('todo')) {
		return 'todo';
	}
	if (
		n.includes('bash') ||
		n.includes('shell') ||
		n === 'echo' ||
		n === 'gettime' ||
		n.includes('mcp') ||
		n.includes('task') ||
		n.includes('web')
	) {
		return 'run';
	}
	return 'other';
}

/** 从 tool_result 文本确定 Write 动词（创建 vs 覆盖）。 */
export function writeSettledVerb(result?: string): 'Created' | 'Wrote' {
	const r = (result ?? '').toLowerCase();
	if (r.includes('created')) {
		return 'Created';
	}
	return 'Wrote';
}

/** 将一次 tool 调用映射为 activity 步骤。 */
