/**
 * AUTO-GENERATED by dismantle-chatstore-phase-b.cjs (Phase B: multiAgentSlice).
 * multiAgent 状态字段 + agent 视图导航 + agent 任务方法自 chatStore.ts 的
 * create() 函数体原样迁移，行为不变；门面在原位置展开
 * createMultiAgentSlice(set, get)。
 */
import type {StoreApi} from 'zustand';
import {
	cancelSessionAgent,
	listSessionAgents,
	loadAgentDetail,
	retrySessionAgent,
	type MultiAgentDeltaStreamEvent,
	type MultiAgentProgressStreamEvent,
	type MultiAgentResultStreamEvent,
	type MultiAgentStatusStreamEvent,
	type MultiAgentTaskStreamEvent,
	type SessionAgentMeta,
} from '@/lib/api';
import {
	getSessionStream,
	patchSessionStream,
} from '@/lib/sessionStreams';
import {
	activeBackendSessionId,
	initAgentNav,
	type ChatState,
} from './preStoreHelpers';

type SetState = StoreApi<ChatState>['setState'];
type GetState = StoreApi<ChatState>['getState'];

const SLICE_KEYS = ['multiAgentTasksBySession', 'agentsBySession', 'agentTranscriptsById', 'liveAgentTextById', 'agentViewStack', 'agentViewIndex', 'pushAgentView', 'backAgentView', 'forwardAgentView', 'resetAgentView', 'openAgentView', 'cancelAgentTask', 'retryAgentTask', 'loadAgentsFor', 'ensureAgentTranscript', 'appendAgentDelta', 'finalizeAgentStream'] as const;

export function createMultiAgentSlice(
	set: SetState,
	get: GetState,
): Pick<ChatState, (typeof SLICE_KEYS)[number]> {
	return {
	multiAgentTasksBySession: {},
	agentsBySession: {},
	agentTranscriptsById: {},
	liveAgentTextById: {},
	...initAgentNav(),

	pushAgentView(agentId) {
		const id = (agentId || '').trim();
		if (!id) {
			return;
		}
		set(s => {
			const stack = s.agentViewStack.slice(0, s.agentViewIndex + 1);
			if (stack[stack.length - 1] === id) {
				return {};
			}
			stack.push(id);
			return {agentViewStack: stack, agentViewIndex: stack.length - 1};
		});
	},

	backAgentView() {
		set(s => ({
			agentViewIndex: Math.max(0, s.agentViewIndex - 1),
		}));
	},

	forwardAgentView() {
		set(s => ({
			agentViewIndex: Math.min(
				s.agentViewStack.length - 1,
				s.agentViewIndex + 1,
			),
		}));
	},

	resetAgentView() {
		set(initAgentNav());
	},

	openAgentView(agentId) {
		const id = (agentId || '').trim();
		if (!id) {
			return;
		}
		get().pushAgentView(id);
		const sessionId = get().activeId;
		if (sessionId) {
			void get().ensureAgentTranscript(sessionId, id);
		}
	},

	async cancelAgentTask(sessionId, agentId) {
		const sid = (sessionId || '').trim();
		const aid = (agentId || '').trim();
		if (!sid || !aid) return false;
		const backendSid = activeBackendSessionId(get().historyById, sid);
		const ok = await cancelSessionAgent(backendSid, aid);
		if (ok) {
			set(s => {
				const list = s.multiAgentTasksBySession[sid] ?? [];
				return {
					multiAgentTasksBySession: {
						...s.multiAgentTasksBySession,
						[sid]: list.map(t =>
							t.agentId === aid
								? {
										...t,
										status: 'failed' as const,
										reason: 'cancelled by user',
										result: t.result || '已取消',
									}
								: t,
						),
					},
				};
			});
		}
		return ok;
	},

	async retryAgentTask(sessionId, agentId) {
		const sid = (sessionId || '').trim();
		const aid = (agentId || '').trim();
		if (!sid || !aid) return false;
		set(s => {
			const list = s.multiAgentTasksBySession[sid] ?? [];
			const key = `${sid}::${aid}`;
			return {
				multiAgentTasksBySession: {
					...s.multiAgentTasksBySession,
					[sid]: list.map(t =>
						t.agentId === aid
							? {
									...t,
									status: 'running' as const,
									reason: undefined,
									result: undefined,
								}
							: t,
					),
				},
				liveAgentTextById: {...s.liveAgentTextById, [key]: ''},
				agentTranscriptsById: {
					...s.agentTranscriptsById,
					[key]: {status: 'running', messages: []},
				},
			};
		});
		const backendSid = activeBackendSessionId(get().historyById, sid);
		const result = await retrySessionAgent(backendSid, aid);
		if (!result) {
			set(s => {
				const list = s.multiAgentTasksBySession[sid] ?? [];
				return {
					multiAgentTasksBySession: {
						...s.multiAgentTasksBySession,
						[sid]: list.map(t =>
							t.agentId === aid
								? {
										...t,
										status: 'failed' as const,
										reason: 'retry failed',
									}
								: t,
						),
					},
				};
			});
			return false;
		}
		set(s => {
			const list = s.multiAgentTasksBySession[sid] ?? [];
			return {
				multiAgentTasksBySession: {
					...s.multiAgentTasksBySession,
					[sid]: list.map(t =>
						t.agentId === aid
							? {
									...t,
									status: result.status,
									result: result.resultPreview,
									reason:
										result.status === 'failed'
											? result.resultPreview
											: undefined,
								}
							: t,
					),
				},
			};
		});
		await get().finalizeAgentStream(sid, aid);
		return result.status === 'done';
	},

	async loadAgentsFor(sessionId) {
		if (!sessionId || !get().sessions.some(s => s.id === sessionId)) {
			return;
		}
		let metas: SessionAgentMeta[] = [];
		try {
			const backendSid = activeBackendSessionId(get().historyById, sessionId);
			metas = await listSessionAgents(backendSid);
		} catch {
			return; // 后端不可达/接口缺失：静默跳过（历史批次合并为尽力而为）。
		}
		if (!get().sessions.some(s => s.id === sessionId) || metas.length === 0) {
			return;
		}
		set(s => ({agentsBySession: {...s.agentsBySession, [sessionId]: metas}}));
		// 历史批次合并进卡片视图（SSE uid 优先；按 agentId 幂等去重）。
		set(s => {
			const existing = s.multiAgentTasksBySession[sessionId] ?? [];
			const knownAgents = new Set(
				existing.map(t => t.agentId).filter(Boolean),
			);
			const merged = [...existing];
			for (const m of metas) {
				if (!m.agentId || knownAgents.has(m.agentId)) {
					continue;
				}
				merged.push({
					uid: m.agentId,
					taskId: m.taskId,
					agentId: m.agentId,
					desc: m.desc,
					status: m.status === 'done' ? 'done' : 'failed',
					reason: m.resultPreview ? undefined : m.status,
					result: m.resultPreview,
					batchAt: m.startedAt,
					...(m.readOnly !== undefined ? {readOnly: m.readOnly} : {}),
					...(m.scope?.length || m.readOnly ? {scope: m.scope ?? []} : {}),
					...(m.inboxCount ? {inboxCount: m.inboxCount} : {}),
				});
			}
			return {
				multiAgentTasksBySession: {
					...s.multiAgentTasksBySession,
					[sessionId]: merged,
				},
			};
		});
	},

	async ensureAgentTranscript(sessionId, agentId, opts) {
		const key = `${sessionId}::${agentId}`;
		const cached = get().agentTranscriptsById[key];
		// 已有快照（含运行中快照）默认复用；运行中由 SubAgentView 轮询 force 刷新。
		if (!opts?.force && cached !== undefined && cached !== null) {
			return;
		}
		const backendSid = activeBackendSessionId(get().historyById, sessionId);
		const detail = await loadAgentDetail(backendSid, agentId);
		if (!detail) {
			// 拉取失败：已有快照则保留；否则置 null 仅作「本轮失败」标记，
			// 不阻塞后续重试（404/网络恢复后轮询会自然覆盖）。
			if (!cached) {
				set(s => ({agentTranscriptsById: {...s.agentTranscriptsById, [key]: null}}));
			}
			return;
		}
		// 静默修复 tool 行状态（侧链无 running 中间态）。
		const messages = detail.messages.map(m =>
			m.role === 'tool'
				? {
						...m,
						toolStatus:
							m.toolStatus ?? (m.text.startsWith('[error]') ? 'error' : 'done'),
					}
				: m,
		);
		set(s => ({
			agentTranscriptsById: {
				...s.agentTranscriptsById,
				[key]: {status: detail.status, messages},
			},
		}));
	},

	appendAgentDelta(sessionId, agentId, text) {
		if (!text) {
			return;
		}
		const key = `${sessionId}::${agentId}`;
		set(s => ({
			liveAgentTextById: {
				...s.liveAgentTextById,
				[key]: (s.liveAgentTextById[key] ?? '') + text,
			},
		}));
	},

	async finalizeAgentStream(sessionId, agentId) {
		const key = `${sessionId}::${agentId}`;
		try {
			await get().ensureAgentTranscript(sessionId, agentId, {force: true});
		} finally {
			set(s => {
				if (!(key in s.liveAgentTextById)) {
					return {};
				}
				const next = {...s.liveAgentTextById};
				delete next[key];
				return {liveAgentTextById: next};
			});
		}
	},

	};
}

export type MultiAgentStreamHandlers = {
	handleAgentCard: (name: string, input: unknown) => void;
	onMultiAgentTask: (ev: Omit<MultiAgentTaskStreamEvent, 'kind'>) => void;
	onMultiAgentResult: (ev: Omit<MultiAgentResultStreamEvent, 'kind'>) => void;
	onMultiAgentProgress: (ev: Omit<MultiAgentProgressStreamEvent, 'kind'>) => void;
	onMultiAgentDelta: (ev: Omit<MultiAgentDeltaStreamEvent, 'kind'>) => void;
	onMultiAgentStatus: (ev: Omit<MultiAgentStatusStreamEvent, 'kind'>) => void;
};

/**
 * 多 Agent 的 SSE 派发，从 streamSendSlice 拆出。每次流式发送
 * 各创建一个实例；持有「本批首张卡片重置 Agent 视图」
 * 的闩锁（multiNavResetDone）。调用方派发前必须先通过
 * settled / sessionStreamActive 守卫。
 */
export function createMultiAgentStreamHandlers(deps: {
	get: GetState;
	set: SetState;
	sessionId: string;
}): MultiAgentStreamHandlers {
	const {get, set, sessionId} = deps;
	let multiNavResetDone = false;
	const ensureNavReset = () => {
		if (!multiNavResetDone) {
			multiNavResetDone = true;
			get().resetAgentView();
		}
	};

	const handleAgentCard = (name: string, input: unknown) => {
		if (name !== 'Agent' && name !== 'Task') {
			return;
		}
		const raw = (input ?? {}) as Record<string, unknown>;
		const taskId = String(raw.task_id ?? raw.taskId ?? '').trim() || 'task';
		const desc = String(raw.desc ?? '').trim().slice(0, 120) || taskId;
		const uid = `pending:${taskId}`;
		set(s => {
			const list = s.multiAgentTasksBySession[sessionId] ?? [];
			if (list.some(t => t.uid === uid || t.taskId === taskId)) {
				return {};
			}
			return {
				multiAgentTasksBySession: {
					...s.multiAgentTasksBySession,
					[sessionId]: [
						...list,
						{
							uid,
							taskId,
							agentId: '',
							desc,
							status: 'pending' as const,
							batchAt: Date.now(),
						},
					],
				},
			};
		});
		ensureNavReset();
	};

	const onMultiAgentTask = (ev: Omit<MultiAgentTaskStreamEvent, 'kind'>) => {
		set(s => {
			const list = s.multiAgentTasksBySession[sessionId] ?? [];
			const pendingUid = `pending:${ev.taskId}`;
			const withoutPending = list.filter(
				t => t.uid !== pendingUid && t.uid !== ev.uid,
			);
			return {
				multiAgentTasksBySession: {
					...s.multiAgentTasksBySession,
					[sessionId]: [
						...withoutPending,
						{
							uid: ev.uid,
							taskId: ev.taskId,
							agentId: ev.agentId,
							desc: ev.desc,
							status:
								ev.status === 'pending' ||
								ev.status === 'done' ||
								ev.status === 'failed'
									? ev.status
									: 'running',
							...(ev.turnId ? {turnId: ev.turnId} : {}),
							...(ev.readOnly !== undefined
								? {readOnly: ev.readOnly}
								: {}),
							...(ev.scope?.length || ev.readOnly
								? {scope: ev.scope ?? []}
								: {}),
							batchAt: Date.now(),
						},
					],
				},
			};
		});
		// 本批次首个卡片出现时回到主视图（保证能看到「正在运行」条）。
		ensureNavReset();
	};

	const onMultiAgentResult = (ev: Omit<MultiAgentResultStreamEvent, 'kind'>) => {
		set(s => {
			const list = s.multiAgentTasksBySession[sessionId] ?? [];
			const byUid = new Map(list.map(t => [t.uid, t]));
			for (const row of ev.tasks) {
				const prev = byUid.get(row.uid);
				// 新出现的行（无对应 task 事件）也补批次时刻，保证可被轮次锚定。
				byUid.set(row.uid,
					prev ? {...prev, ...row} : {...row, batchAt: Date.now()},
				);
			}
			return {
				multiAgentTasksBySession: {
					...s.multiAgentTasksBySession,
					[sessionId]: Array.from(byUid.values()),
				},
			};
		});
		// 服务端 meta 兜底（含历史批合并），供刷新/重进后回放。
		void get().loadAgentsFor(sessionId);
		// 全批落定：逐个交接增量缓冲（进度帧已逐个处理，这里兜底）。
		for (const row of ev.tasks) {
			if (row.agentId) {
				void get().finalizeAgentStream(sessionId, row.agentId);
			}
		}
	};

	const onMultiAgentProgress = (ev: Omit<MultiAgentProgressStreamEvent, 'kind'>) => {
		set(s => {
			const list = s.multiAgentTasksBySession[sessionId] ?? [];
			const pendingUid = `pending:${ev.taskId}`;
			const idx = list.findIndex(
				t => t.uid === ev.uid || t.uid === pendingUid,
			);
			if (idx < 0) {
				// 进度先于 task 帧：补一张卡。
				return {
					multiAgentTasksBySession: {
						...s.multiAgentTasksBySession,
						[sessionId]: [
							...list,
							{
								uid: ev.uid,
								taskId: ev.taskId,
								agentId: ev.agentId,
								desc: ev.taskId,
								status: ev.status,
								reason: ev.reason,
								result: ev.result,
								batchAt: Date.now(),
							},
						],
					},
				};
			}
			return {
				multiAgentTasksBySession: {
					...s.multiAgentTasksBySession,
					[sessionId]: list.map((t, i) =>
						i === idx
							? {
									...t,
									uid: ev.uid || t.uid,
									agentId: ev.agentId || t.agentId,
									status: ev.status,
									reason: ev.reason ?? t.reason,
									result: ev.result ?? t.result,
								}
							: t,
					),
				},
			};
		});
		// 单任务落定：立即刷该子 agent 的终态快照并交接增量缓冲。
		if (
			ev.status !== 'running' &&
			ev.status !== 'pending' &&
			ev.agentId
		) {
			void get().finalizeAgentStream(sessionId, ev.agentId);
		}
	};

	const onMultiAgentDelta = (ev: Omit<MultiAgentDeltaStreamEvent, 'kind'>) => {
		if (!ev.agentId || !ev.text) {
			return;
		}
		get().appendAgentDelta(sessionId, ev.agentId, ev.text);
	};

	const onMultiAgentStatus = (ev: Omit<MultiAgentStatusStreamEvent, 'kind'>) => {
		const text = (ev.text || '').trim();
		if (!text) {
			return;
		}
		set(s => {
			const stream = getSessionStream(s, sessionId);
			// 已有正文时不再用状态行盖住；仅空等阶段更新 Composer。
			if (stream.streamingText.trim()) {
				return {};
			}
			return {
				sessionStreams: patchSessionStream(
					s.sessionStreams,
					sessionId,
					{statusText: text},
				),
			};
		});
	};

	return {
		handleAgentCard,
		onMultiAgentTask,
		onMultiAgentResult,
		onMultiAgentProgress,
		onMultiAgentDelta,
		onMultiAgentStatus,
	};
}
