/**
 * AUTO-GENERATED by dismantle-chatstore-slice.cjs (Phase C: remoteMirrorSlice).
 * Methods moved verbatim from chatStore.ts create() body. Behavior unchanged;
 * facade spreads createRemoteMirrorSlice(set, get) at the former position.
 */
import type {StoreApi} from 'zustand';
import {
	DEFAULT_SPACE_ID,
	replaceMessages,
	saveSession,
} from '@/lib/db';
import {
	clearTodoDismissal,
} from '@/lib/todoDismissals';
import {
	formatToolInputForUi,
} from '@/lib/sanitizeToolInput';
import {
	type ChatMessage,
	type ChatSession,
} from '@/lib/types';
import {
	uid,
} from '@/lib/utils';
import {
	setStreamingTextSignal,
	streamSignalsEnabled,
} from '@/lib/streamSignal';
import {
	getSessionStream,
	isAbortDead,
	patchSessionStream,
	sessionStreamBusy,
} from '@/lib/sessionStreams';
import {
	clearSessionStreamState,
	commitDrainForSession,
	type ChatState,
} from './preStoreHelpers';
import {
	isTodoWriteName,
	snapshotFromTodoTool,
} from './streamHelpers';

type SetState = StoreApi<ChatState>['setState'];
type GetState = StoreApi<ChatState>['getState'];

export const remoteMirror = { targetSid: null as string | null };

function resolveRemoteMirrorTarget(
	state: Pick<ChatState, 'sessions' | 'messagesById'>,
): string | null {
	const locked = remoteMirror.targetSid;
	if (!locked) {
		return null;
	}
	const alive =
		state.sessions.some(s => s.id === locked) &&
		state.messagesById[locked] !== undefined;
	if (!alive) {
		remoteMirror.targetSid = null;
		return null;
	}
	return locked;
}

const SLICE_KEYS = ['appendRemoteMessage', 'appendLocalNote', 'syncRemoteStream', 'applyRemoteToolCall', 'applyRemoteToolResult', 'commitRemoteStream', 'finishRemoteStream'] as const;

export function createRemoteMirrorSlice(
	set: SetState,
	get: GetState,
): Pick<ChatState, (typeof SLICE_KEYS)[number]> {
	return {
	appendRemoteMessage(role, text) {
		const trimmed = text.trim();
		if (!trimmed) {
			return;
		}
		let sessionId = resolveRemoteMirrorTarget(get());
		if (!sessionId) {
			sessionId = get().activeId;
			if (!sessionId || !get().sessions.some(s => s.id === sessionId)) {
				sessionId = get().sessions[0]?.id ?? null;
			}
		}
		if (!sessionId) {
			const spaceId = get().activeSpaceId || DEFAULT_SPACE_ID;
			const createdAt = Date.now();
			const session: ChatSession = {
				id: uid('sess'),
				spaceId,
				title: '远程',
				createdAt,
				updatedAt: createdAt,
			};
			sessionId = session.id;
			set(s => ({
				sessions: [session, ...s.sessions],
				messagesById: {
					...s.messagesById,
					[session.id]: s.messagesById[session.id] ?? [],
				},
				activeId: session.id,
				activeSpaceId: spaceId,
			}));
			void saveSession(session).catch(() => {
				/* 镜像失败不打断远程 */
			});
		}
		remoteMirror.targetSid = sessionId;
		const prev = get().messagesById[sessionId] ?? [];
		const last = prev[prev.length - 1];
		if (last && last.role === role && last.text === trimmed) {
			return;
		}
		const now = Date.now();
		const msg: ChatMessage = {
			id: uid('msg'),
			role,
			text: trimmed,
			createdAt: now,
			source: 'remote',
		};
		const next = [...prev, msg];
		const sessions = get().sessions;
		const idx = sessions.findIndex(s => s.id === sessionId);
		let nextSessions = sessions;
		if (idx >= 0) {
			const updated = {...sessions[idx]!, updatedAt: now};
			if (idx === 0) {
				nextSessions = [updated, ...sessions.slice(1)];
			} else {
				nextSessions = [
					updated,
					...sessions.slice(0, idx),
					...sessions.slice(idx + 1),
				];
			}
		}
		set({
			sessions: nextSessions,
			messagesById: {...get().messagesById, [sessionId]: next},
		});
		void replaceMessages(sessionId, next).catch(() => {
			/* 镜像失败不打断远程 */
		});
	},

	appendLocalNote(text) {
		const sessionId = get().activeId;
		if (!sessionId) {
			return;
		}
		const trimmed = String(text ?? '').trim();
		if (!trimmed) {
			return;
		}
		// 防崩溃：超长结果不进列表（状态/帮助类输出本身有限）
		const MAX_NOTE = 8_000;
		const body = trimmed.length > MAX_NOTE ? trimmed.slice(0, MAX_NOTE) + '…' : trimmed;
		const prev = get().messagesById[sessionId] ?? [];
		const msg: ChatMessage = {
			id: uid('msg'),
			role: 'system',
			text: body,
			createdAt: Date.now(),
			uiOnly: true,
		};
		set({
			messagesById: {...get().messagesById, [sessionId]: [...prev, msg]},
		});
	},

	syncRemoteStream(text, status) {
		const sessionId =
			resolveRemoteMirrorTarget(get()) ??
			get().activeId ??
			get().sessions[0]?.id ??
			null;
		if (!sessionId) {
			return;
		}
		commitDrainForSession(sessionId);
		const cur = get();
		const stream = getSessionStream(cur, sessionId);
		if (stream.abortRef && !isAbortDead(stream.abortRef) && !stream.remoteStreaming) {
			return;
		}
		remoteMirror.targetSid = sessionId;
		const nextText = text ?? '';
		if (
			stream.remoteStreaming &&
			stream.streamingText === nextText &&
			stream.streamingShown === nextText &&
			(nextText
				? stream.statusText === ''
				: stream.statusText === (status || 'thinking…'))
		) {
			return;
		}
		set(s => ({
			sessionStreams: patchSessionStream(s.sessionStreams, sessionId, {
				isLoading: true,
				remoteStreaming: true,
				streamingText: nextText,
				streamingShown: nextText,
				statusText: nextText ? '' : status || 'thinking…',
				draining: false,
			}),
		}));
		if (streamSignalsEnabled && get().activeId === sessionId) {
			setStreamingTextSignal(nextText);
		}
	},

	applyRemoteToolCall(name, input) {
		const sessionId =
			resolveRemoteMirrorTarget(get()) ??
			get().activeId ??
			get().sessions[0]?.id ??
			null;
		if (!sessionId) {
			return;
		}
		commitDrainForSession(sessionId);
		const cur = get();
		const stream = getSessionStream(cur, sessionId);
		if (stream.abortRef && !isAbortDead(stream.abortRef) && !stream.remoteStreaming) {
			return;
		}
		remoteMirror.targetSid = sessionId;
		const msgs = [...(cur.messagesById[sessionId] ?? [])];
		if (stream.streamingText.trim()) {
			msgs.push({
				id: uid('msg'),
				role: 'assistant',
				text: stream.streamingText,
				createdAt: Date.now(),
				source: 'remote',
			});
		}
		const toolId = uid('tool');
		const toolInput = formatToolInputForUi(input);
		msgs.push({
			id: toolId,
			role: 'tool',
			toolName: name,
			toolInput,
			toolStatus: 'running',
			text: '',
			createdAt: Date.now(),
			source: 'remote',
		});
		const patch: Partial<ChatState> = {
			messagesById: {...cur.messagesById, [sessionId]: msgs},
		};
		if (isTodoWriteName(name)) {
			try {
				clearTodoDismissal(sessionId);
				const snap = snapshotFromTodoTool({
					id: toolId,
					input: toolInput,
					running: true,
				});
				if (snap) {
					patch.sessionTodosById = {
						...cur.sessionTodosById,
						[sessionId]: snap,
					};
				}
			} catch {
				/* 远程 Todo 快照失败不挡工具卡片 */
			}
		}
		set(s => ({
			...patch,
			sessionStreams: patchSessionStream(s.sessionStreams, sessionId, {
				isLoading: true,
				remoteStreaming: true,
				streamingText: '',
				streamingShown: '',
				statusText: '',
				draining: false,
			}),
		}));
		if (streamSignalsEnabled && get().activeId === sessionId) {
			setStreamingTextSignal('');
		}
		void replaceMessages(sessionId, msgs).catch(() => {
			/* 镜像失败不打断远程 */
		});
	},

	applyRemoteToolResult(name, output, isError) {
		const sessionId =
			resolveRemoteMirrorTarget(get()) ??
			get().activeId ??
			get().sessions[0]?.id ??
			null;
		if (!sessionId) {
			return;
		}
		const cur = get();
		const stream = getSessionStream(cur, sessionId);
		if (stream.abortRef && !isAbortDead(stream.abortRef) && !stream.remoteStreaming) {
			return;
		}
		const msgs = [...(cur.messagesById[sessionId] ?? [])];
		let idx = -1;
		for (let i = msgs.length - 1; i >= 0; i -= 1) {
			const m = msgs[i]!;
			if (
				m.role === 'tool' &&
				m.toolName === name &&
				(m.toolStatus === 'running' || m.toolStatus === 'waiting')
			) {
				idx = i;
				break;
			}
		}
		const body = isError ? `[error]\n${output}` : output;
		if (idx >= 0) {
			const prev = msgs[idx]!;
			msgs[idx] = {
				...prev,
				text: body,
				toolStatus: isError ? 'error' : 'done',
			};
		} else {
			msgs.push({
				id: uid('tool'),
				role: 'tool',
				toolName: name,
				toolInput: '',
				toolStatus: isError ? 'error' : 'done',
				text: body,
				createdAt: Date.now(),
				source: 'remote',
			});
		}
		remoteMirror.targetSid = sessionId;
		set(s => ({
			messagesById: {...cur.messagesById, [sessionId]: msgs},
			sessionStreams: patchSessionStream(s.sessionStreams, sessionId, {
				isLoading: true,
				remoteStreaming: true,
				statusText: '',
				draining: false,
			}),
		}));
		void replaceMessages(sessionId, msgs).catch(() => {
			/* 镜像失败不打断远程 */
		});
	},

	commitRemoteStream(text) {
		const sessionId =
			resolveRemoteMirrorTarget(get()) ?? get().activeId ?? null;
		const trimmed = (text || '').trim();
		if (trimmed) {
			const msgs = sessionId ? (get().messagesById[sessionId] ?? []) : [];
			const last = msgs[msgs.length - 1];
			const norm = (s: string) => s.replace(/\s+/g, ' ').trim();
			const nTrim = norm(trimmed);
			if (
				last?.role === 'assistant' &&
				(norm(last.text) === nTrim ||
					(nTrim.startsWith(norm(last.text)) && norm(last.text).length > 16))
			) {
				// 已由流式 finalize 写入过，跳过重复 outbound
			} else {
				get().appendRemoteMessage('assistant', trimmed);
			}
		}
		if (!sessionId) {
			return;
		}
		const stream = getSessionStream(get(), sessionId);
		if (!stream.remoteStreaming && stream.abortRef && !isAbortDead(stream.abortRef)) {
			return;
		}
		if (stream.remoteStreaming || sessionStreamBusy(get(), sessionId)) {
			set(s => ({
				sessionStreams: clearSessionStreamState(s.sessionStreams, sessionId),
			}));
			remoteMirror.targetSid = null;
			if (streamSignalsEnabled && get().activeId === sessionId) {
				setStreamingTextSignal('');
			}
		}
	},

	finishRemoteStream() {
		const sessionId = remoteMirror.targetSid;
		if (!sessionId) {
			return;
		}
		const stream = getSessionStream(get(), sessionId);
		if (!stream.remoteStreaming) {
			return;
		}
		set(s => ({
			sessionStreams: clearSessionStreamState(s.sessionStreams, sessionId),
		}));
		remoteMirror.targetSid = null;
		if (streamSignalsEnabled && get().activeId === sessionId) {
			setStreamingTextSignal('');
		}
	},
	};
}
