/**
 * AUTO-GENERATED by dismantle-chatstore-slice.cjs (Phase G: uiChromeSlice).
 * Methods moved verbatim from chatStore.ts create() body. Behavior unchanged;
 * facade spreads createUiChromeSlice(set, get) at the former position.
 */
import type {StoreApi} from 'zustand';
import {
	normalizeAgentMode,
} from '@/lib/agentMode';
import {useWorkspaceStore} from '@/stores/workspaceStore';
import {useSettingsStore} from '@/stores/settingsStore';
import {
	type AskUserPendingStreamEvent,
	type AskUserResolvedStreamEvent,
	type PermissionPendingStreamEvent,
	type PermissionResolvedStreamEvent,
	type PlanPendingStreamEvent,
	type PlanResolvedStreamEvent,
} from '@/lib/api';
import {
	pendingMatchesActiveSession,
	sessionErrorBannerPatch,
} from '@/lib/pendingForSession';
import {
	sessionStreamActive,
} from '@/lib/sessionStreams';
import {
	toast,
} from '@/lib/toast';
import {
	useCommandPaletteStore,
} from '@/stores/commandPaletteStore';
import {
	type ChatState,
	type PendingPermissionInfo,
} from './preStoreHelpers';

const PENDING_PERMISSION_KEY = 'xy:pendingPermission';

export function readPendingPermission(): PendingPermissionInfo | null {
	try {
		const raw = localStorage.getItem(PENDING_PERMISSION_KEY);
		return raw ? (JSON.parse(raw) as PendingPermissionInfo) : null;
	} catch {
		return null;
	}
}

export function writePendingPermission(value: PendingPermissionInfo | null): void {
	try {
		localStorage.setItem(PENDING_PERMISSION_KEY, JSON.stringify(value));
	} catch {
		/* ignore */
	}
}

export const savedPendingPermission = readPendingPermission();

type SetState = StoreApi<ChatState>['setState'];
type GetState = StoreApi<ChatState>['getState'];

const SLICE_KEYS = ['setSidebarOpen', 'setImmersive', 'setPendingPermission', 'setPendingAsk', 'setPendingPlan', 'setAgentMode', 'requestSearchFocus', 'requestComposerInsert', 'requestComposerFocus', 'clearErrorBanner'] as const;

export function createUiChromeSlice(
	set: SetState,
	get: GetState,
): Pick<ChatState, (typeof SLICE_KEYS)[number]> {
	return {
	setSidebarOpen(open) {
		set({sidebarOpen: open});
	},
	setImmersive(open) {
		// P3-⑫：进入沉浸态时收起侧边栏并关闭工作区/用量面板；退出时恢复侧边栏。
		set({immersive: open});
		if (open) {
			// 关闭侧边栏、工作区、用量覆盖层（保持对话可见）。
			set({sidebarOpen: false});
			void useWorkspaceStore.getState().setOpen(false);
			void useSettingsStore.getState().closeUsage?.();
		}
	},

	setPendingPermission(value) {
		set({pendingPermission: value});
		writePendingPermission(value);
	},

	setPendingAsk(value) {
		set({pendingAsk: value});
	},

	setPendingPlan(value) {
		set({pendingPlan: value});
	},

	setAgentMode(mode) {
		set({agentMode: normalizeAgentMode(mode)});
	},

	requestSearchFocus() {
		useCommandPaletteStore.getState().openPalette();
	},

	requestComposerInsert(file) {
		const name = file.name.trim() || 'selection';
		const path = file.path?.trim() || undefined;
		const text = file.text;
		// 整文件用 path 引用；选区用 text。二者皆空则忽略。
		if (!path && !text) {
			return;
		}
		// 防崩溃：超大片段不进 Composer 状态（Cursor 也不会把整仓文件塞进输入框）
		const MAX_SNIPPET = 48_000;
		if (text != null && text.length > MAX_SNIPPET) {
			toast.error(
				`选区过大（>${Math.round(MAX_SNIPPET / 1000)}KB），请缩小选区或改为添加文件引用`,
			);
			return;
		}
		set(s => ({
			lastComposerInsert: {name, text, path},
			composerInsertSeq: s.composerInsertSeq + 1,
			composerFocusSeq: s.composerFocusSeq + 1,
		}));
	},

	requestComposerFocus() {
		set(s => ({composerFocusSeq: s.composerFocusSeq + 1}));
	},

			clearErrorBanner() {
		if (get().errorBanner) {
			set(sessionErrorBannerPatch(null, null));
		}
	},
	};
}

export type PendingStreamHandlers = {
	onPermissionPending: (ev: PermissionPendingStreamEvent) => void;
	onPermissionResolved: (ev: PermissionResolvedStreamEvent) => void;
	onAskUserPending: (ev: AskUserPendingStreamEvent) => void;
	onAskUserResolved: (ev: AskUserResolvedStreamEvent) => void;
	onPlanPending: (ev: PlanPendingStreamEvent) => void;
	onPlanResolved: (ev: PlanResolvedStreamEvent) => void;
};

/**
 * Pending permission / ask / plan SSE dispatch, extracted from streamSendSlice.
 * Callers must apply the sessionStreamActive guard before dispatching.
 */
export function createPendingStreamHandlers(deps: {
	get: GetState;
	sessionId: string;
}): PendingStreamHandlers {
	const {get, sessionId} = deps;

	const onPermissionPending = (ev: PermissionPendingStreamEvent) => {
		if (!sessionStreamActive(get(), sessionId)) return;
		get().setPendingPermission?.({
			requestId: ev.requestId,
			toolName: ev.toolName,
			prompt: ev.prompt,
			reason: ev.reason,
			sessionId,
			choices: ev.choices,
			peerSummary: ev.peerSummary,
			intent: ev.intent,
			expiresAt: ev.expiresAt ?? null,
		});
	};
	const onPermissionResolved = (_ev: PermissionResolvedStreamEvent) => {
		const pending = get().pendingPermission;
		if (
			pending &&
			pendingMatchesActiveSession(pending.sessionId, sessionId)
		) {
			get().setPendingPermission?.(null);
		}
	};
	const onAskUserPending = (ev: AskUserPendingStreamEvent) => {
		if (!sessionStreamActive(get(), sessionId)) return;
		get().setPendingAsk?.({
			requestId: ev.requestId,
			question: ev.question,
			options: ev.options ?? [],
			default: ev.default,
			expiresAt: ev.expiresAt,
			sessionId,
		});
	};
	const onAskUserResolved = (_ev: AskUserResolvedStreamEvent) => {
		const pending = get().pendingAsk;
		if (
			pending &&
			pendingMatchesActiveSession(pending.sessionId, sessionId)
		) {
			get().setPendingAsk?.(null);
		}
	};
	const onPlanPending = (ev: PlanPendingStreamEvent) => {
		if (!sessionStreamActive(get(), sessionId)) return;
		get().setPendingPlan?.({
			requestId: ev.requestId,
			plan: ev.plan,
			sessionId: ev.sessionId,
			turnId: ev.turnId,
			expiresAt: ev.expiresAt,
		});
	};
	const onPlanResolved = (_ev: PlanResolvedStreamEvent) => {
		const pending = get().pendingPlan;
		if (
			pending &&
			pendingMatchesActiveSession(pending.sessionId, sessionId)
		) {
			get().setPendingPlan?.(null);
		}
	};

	return {
		onPermissionPending,
		onPermissionResolved,
		onAskUserPending,
		onAskUserResolved,
		onPlanPending,
		onPlanResolved,
	};
}
