/**
 * AUTO-GENERATED by dismantle-messagelist.cjs (spec m2: PromptBubble).
 * Blocks moved verbatim from components/MessageList.tsx. Behavior unchanged.
 */
import {
	memo,
	useContext,
	useLayoutEffect,
	useRef,
	useState,
	type MouseEvent,
	type MutableRefObject,
	type ReactNode,
} from 'react';
import {
	createPortal,
} from 'react-dom';
import {
	ArrowUp,
	ChevronDown,
	Paperclip,
	Plus,
	Square,
	X,
	ZoomIn,
} from 'lucide-react';
import {
	cancelFrameTask,
	createFrameKey,
	scheduleFrameRead,
} from '@/lib/frameScheduler';
import {
	mediaUrl,
} from '@/lib/api';
import {
	type DraftAttachment,
} from '@/lib/composerDrafts';
import {
	cn,
} from '@/lib/utils';
import {
	userMessageMenuItems,
} from '@/lib/contextMenus';
import {
	showContextMenu,
} from '../ui/ContextMenu';
import {
	ModelPicker,
} from '../ModelPicker';
import {
	ImageReaderDialog,
	type ImageReaderSource,
} from '../ImageReader';
import {
	UserMarkdownText,
} from '../UserMarkdownText';
import {
	EditPortalHostContext,
	PROMPT_CHIP_MAX_PX,
	syncPromptClampOverflow,
} from '../sticky';

export function PromptTextClamp({children}: {children: ReactNode}) {
	const ref = useRef<HTMLDivElement>(null);
	const frameKeyRef = useRef(createFrameKey('prompt-clamp'));
	useLayoutEffect(() => {
		const el = ref.current;
		if (!el) {
			return;
		}
		const key = frameKeyRef.current;
		const sync = () => {
			scheduleFrameRead(key, () => syncPromptClampOverflow(el));
		};
		sync();
		const ro =
			typeof ResizeObserver !== 'undefined' ? new ResizeObserver(sync) : null;
		ro?.observe(el);
		/* 宿主 chip 尺寸也纳入观察：统一查看上限（--xy-prompt-view-cap）随视口
		   变化时，chip 可见高改变而 clamp 内容高不变，只有 observe chip 才能重估
		   overflow 标记（长气泡渐隐提示随 cap 联动）。 */
		const chip = el.closest<HTMLElement>(
			'.xy-user-prompt, [data-xy-prompt-chip]',
		);
		if (chip) {
			ro?.observe(chip);
		}
		const sticky = el.closest('.xy-prompt-sticky');
		const mo =
			sticky && typeof MutationObserver !== 'undefined'
				? new MutationObserver(sync)
				: null;
		mo?.observe(sticky!, {
			attributes: true,
			attributeFilter: ['class', 'data-xy-stuck'],
		});
		return () => {
			ro?.disconnect();
			mo?.disconnect();
			cancelFrameTask(key);
		};
	}, [children]);
	return (
		<div ref={ref} className="xy-prompt-clamp">
			{children}
		</div>
	);
}

export type PromptBubbleProps = {
	text: string;
	mediaRefs?: string[];
	rise?: boolean;
	editable?: boolean;
	isEditing?: boolean;
	onEdit?: (event?: MouseEvent<HTMLDivElement>) => void;
	editingText?: string;
	onEditTextChange?: (text: string) => void;
	editingSubmitting?: boolean;
	cancelEdit?: () => void;
	submitEdit?: () => void;
	model?: string;
	modelOpen?: boolean;
	modelMenuId?: string;
	toggleModel?: () => void;
	closeModel?: () => void;
	editingTextareaRef?: MutableRefObject<HTMLTextAreaElement | null>;
	editModelMenuRef?: MutableRefObject<HTMLDivElement | null>;
promptEditRef?: MutableRefObject<HTMLDivElement | null>;
	editingFilePickerOpenRef: MutableRefObject<boolean>;
	editingFileInputRef?: MutableRefObject<HTMLInputElement | null>;
	editingAttachments?: DraftAttachment[];
			editingExistingMediaRefs?: string[];

	onEditAttachmentPick?: (files: FileList | File[] | null) => void;
	onRemoveEditAttachment?: (id: string) => void;
	editingUploading?: boolean;
	anyStreaming?: boolean;
	stopGeneration?: () => void;
	resizeEditingTextarea?: () => void;
	/** 吸顶编辑：流内锁高，编辑 UI 只走 portal */
	lockEditFlow?: boolean;
	/** 流内占位高度（进编辑初值 ≤88，展开后可跟气泡长高） */
	editFlowHeight?: number;
	/** 取消中：先关底栏动画，占位收回后再拆 portal */
	editClosing?: boolean;
};

export function shallowArrayEqual<T>(
	a: readonly T[] | undefined,
	b: readonly T[] | undefined,
): boolean {
	if (a === b) {
		return true;
	}
	if (!a || !b || a.length !== b.length) {
		return false;
	}
	for (let i = 0; i < a.length; i += 1) {
		if (a[i] !== b[i]) {
			return false;
		}
	}
	return true;
}

export function promptBubblePropsAreEqual(
	prev: PromptBubbleProps,
	next: PromptBubbleProps,
): boolean {
	return (
		prev.text === next.text &&
		shallowArrayEqual(prev.mediaRefs, next.mediaRefs) &&
		prev.rise === next.rise &&
		prev.editable === next.editable &&
		prev.isEditing === next.isEditing &&
		prev.onEdit === next.onEdit &&
		prev.editingText === next.editingText &&
		prev.onEditTextChange === next.onEditTextChange &&
		prev.editingSubmitting === next.editingSubmitting &&
		prev.cancelEdit === next.cancelEdit &&
		prev.submitEdit === next.submitEdit &&
		prev.model === next.model &&
		prev.modelOpen === next.modelOpen &&
		prev.modelMenuId === next.modelMenuId &&
		prev.toggleModel === next.toggleModel &&
		prev.closeModel === next.closeModel &&
		prev.editingTextareaRef === next.editingTextareaRef &&
		prev.editModelMenuRef === next.editModelMenuRef &&
		prev.promptEditRef === next.promptEditRef &&
		prev.editingFilePickerOpenRef === next.editingFilePickerOpenRef &&
		prev.editingFileInputRef === next.editingFileInputRef &&
		shallowArrayEqual(prev.editingAttachments, next.editingAttachments) &&
		shallowArrayEqual(
			prev.editingExistingMediaRefs,
			next.editingExistingMediaRefs,
		) &&
		prev.onEditAttachmentPick === next.onEditAttachmentPick &&
		prev.onRemoveEditAttachment === next.onRemoveEditAttachment &&
		prev.editingUploading === next.editingUploading &&
		prev.anyStreaming === next.anyStreaming &&
		prev.stopGeneration === next.stopGeneration &&
		prev.resizeEditingTextarea === next.resizeEditingTextarea &&
		prev.lockEditFlow === next.lockEditFlow &&
		prev.editFlowHeight === next.editFlowHeight &&
		prev.editClosing === next.editClosing
	);
}

export const PromptBubble = memo(function PromptBubble({
	text,
	mediaRefs = [],
	rise,
	editable = false,
	isEditing = false,
	onEdit,
	editingText = text,
	onEditTextChange,
	editingSubmitting = false,
	cancelEdit,
	submitEdit,
	model = '',
	modelOpen = false,
	modelMenuId = '',
	toggleModel,
	closeModel,
	editingTextareaRef,
	editModelMenuRef,
promptEditRef,
		editingFilePickerOpenRef,
	editingFileInputRef,
	editingAttachments = [],
			editingExistingMediaRefs = [],

	onEditAttachmentPick,
	onRemoveEditAttachment,
	editingUploading = false,
	anyStreaming = false,
	stopGeneration,
	resizeEditingTextarea,
	lockEditFlow = false,
	editFlowHeight = PROMPT_CHIP_MAX_PX,
	editClosing = false,
}: PromptBubbleProps) {
	const remote = text.startsWith('[远程]');
	const body = remote ? text.replace(/^\[远程\]\s*/, '') : text;
	const canEdit = editable && !remote;
	const editing = canEdit && isEditing;
	const editImages = editingAttachments.filter(
		(a): a is Extract<DraftAttachment, {kind: 'image'}> => a.kind === 'image',
	);
			const editFiles = editingAttachments.filter(
			(a): a is Extract<DraftAttachment, {kind: 'file'}> => a.kind === 'file',
		);
		const [previewImage, setPreviewImage] = useState<ImageReaderSource | null>(null);
		const editPortalHost = useContext(EditPortalHostContext);
		/* 预览后编辑（选项A）：编辑态默认渲染 Markdown 预览（与查看态同源），
		   点击/聚焦预览才切到原生 textarea 真正编辑，消除"查看=富文本/编辑=纯文本"的违和。 */
		const [editPreviewOpen, setEditPreviewOpen] = useState(true);
		/* 每次进入编辑态都回到预览（同一消息再进也预览）。 */
		useLayoutEffect(() => {
			if (editing) {
				setEditPreviewOpen(true);
			}
		}, [editing]);
		/* 关闭预览 → 切到 textarea 时聚焦（便于直接输入）。 */
		const openEditorFromPreview = () => setEditPreviewOpen(false);
		useLayoutEffect(() => {
			if (editing && !editPreviewOpen) {
				editingTextareaRef?.current?.focus({preventScroll: true});
				resizeEditingTextarea?.();
			}
		}, [editing, editPreviewOpen, editingTextareaRef, resizeEditingTextarea]);
		/* 吸顶编辑会 portal 重挂载控件；若首帧就带 is-open，0fr→1fr 过渡会被跳过 */
		const [controlsOpen, setControlsOpen] = useState(false);
		useLayoutEffect(() => {
			if (!editing || editClosing) {
				setControlsOpen(false);
				return;
			}
			setControlsOpen(false);
			let cancelled = false;
			const outer = requestAnimationFrame(() => {
				requestAnimationFrame(() => {
					if (!cancelled) {
						setControlsOpen(true);
					}
				});
			});
			return () => {
				cancelled = true;
				cancelAnimationFrame(outer);
			};
		}, [editing, editPortalHost, editClosing]);

		const chip = (
		<div
			data-xy-prompt-chip
			data-prompt-text={text}
ref={editing ? promptEditRef : undefined}
			className={cn(
				'xy-user-prompt xy-surface xy-user-bubble rounded-2xl px-4 pt-3.5 pb-2.5',
				/* 编辑态必须 visible，否则底部控件 0fr→1fr 展开会被裁掉、看不到动画 */
				editing ? 'overflow-visible' : 'overflow-hidden',
				editing && editPortalHost ? 'w-full min-w-0' : 'mx-auto max-w-3xl',
				canEdit && !editing && 'cursor-text',
				rise && 'anim-rise',
				editing && 'xy-editing-bubble',
				/* 收起编辑：max-height 从 121 渐缩到查看态 96（跨帧 CSS 过渡），
				   配合占位同步渐缩，退出编辑不再同帧硬切、瞬移。 */
				editClosing && 'xy-editing-bubble-closing',
			)}
			onClick={!editing && canEdit ? onEdit : undefined}
			onContextMenu={
				!editing
					? event => {
							showContextMenu(
								event,
								userMessageMenuItems({
									text: body,
									canEdit,
									onEdit,
								}),
								'用户消息',
							);
					  }
					: undefined
			}
			onKeyDown={
				!editing && canEdit
					? event => {
							if (event.key === 'Enter' || event.key === ' ') {
								event.preventDefault();
								onEdit?.();
							}
					  }
					: undefined
			}
			role={!editing && canEdit ? 'button' : undefined}
			tabIndex={!editing && canEdit ? 0 : undefined}
			aria-label={!editing && canEdit ? '编辑这条消息' : undefined}
		>
			{remote ? (
				<p className="mb-1 font-mono text-[10px] tracking-wide text-accent">
					[远程]
				</p>
			) : null}
				{editing ? (
					<>
													{editingExistingMediaRefs.length > 0 || editImages.length > 0 || editFiles.length > 0 ? (
								<div className="grid max-w-[20rem] grid-cols-[repeat(auto-fill,minmax(3.5rem,1fr))] items-center gap-2 border-b border-line/40 px-3 pt-2 pb-2">
									{editingExistingMediaRefs.map((ref, index) => {
										const src = mediaUrl(ref);
										return src ? (
											<button
												key={`existing-${ref}-${index}`}
												type="button"
												aria-label="查看历史图片"
												onClick={event => {
													event.stopPropagation();
													setPreviewImage({src, alt: '已发送图片', title: '历史图片预览'});
												}}
												className="group relative aspect-square min-w-0 cursor-zoom-in overflow-hidden rounded-xl border border-line/70 bg-paper-deep/60 p-0 text-left"
											>
												<img src={src} alt="已发送图片" loading="lazy" decoding="async" className="h-full w-full object-cover" draggable={false} />
												<span className="pointer-events-none absolute right-1 bottom-1 flex h-6 w-6 items-center justify-center rounded-full bg-ink/60 text-paper opacity-0 shadow-sm transition-opacity duration-150 group-hover:opacity-100 group-focus-within:opacity-100">
													<ZoomIn className="h-3.5 w-3.5" strokeWidth={1.9} />
												</span>
											</button>
										) : null;
									})}

																	{editImages.map(image => (
										<div
											key={image.id}
											className="anim-pop group relative aspect-square min-w-0 overflow-hidden rounded-xl border border-line/70 bg-paper-deep/60"
										>
											<button
												type="button"
												aria-label={`查看原图：${image.name}`}
												onClick={event => {
													event.stopPropagation();
													setPreviewImage({src: image.previewUrl, alt: image.name, title: `原图预览：${image.name}`});
												}}
												className="absolute inset-0 cursor-zoom-in border-0 bg-transparent p-0 text-left"
											>
												<img src={image.previewUrl} alt={image.name} loading="lazy" decoding="async" className="h-full w-full object-cover" draggable={false} />
												<span className="pointer-events-none absolute right-1 bottom-1 flex h-6 w-6 items-center justify-center rounded-full bg-ink/60 text-paper opacity-0 shadow-sm transition-opacity duration-150 group-hover:opacity-100 group-focus-within:opacity-100">
													<ZoomIn className="h-3.5 w-3.5" strokeWidth={1.9} />
												</span>
											</button>
											<button
												type="button"
												aria-label={`移除 ${image.name}`}
												onClick={event => {
													event.stopPropagation();
													onRemoveEditAttachment?.(image.id);
												}}
												className="xy-icon-btn xy-hover-reveal absolute top-0.5 right-0.5 flex h-5 w-5 items-center justify-center rounded-full bg-ink/75 text-paper opacity-0 transition-opacity duration-150 group-hover:opacity-100 group-focus-within:opacity-100 hover:bg-ink"
											>
												<X className="h-3 w-3" />
											</button>
										</div>
									))}

								{editFiles.map(file => (
									<span
										key={file.id}
										className="anim-pop inline-flex max-w-full items-center gap-1.5 rounded-lg border border-line bg-paper px-2 py-0.5 font-mono text-[11px] text-ink-soft"
									>
										<Paperclip className="h-3 w-3 shrink-0 text-accent" />
										<span className="truncate">{file.name}</span>
										<button type="button" onClick={() => onRemoveEditAttachment?.(file.id)} className="xy-icon-btn shrink-0 text-mute hover:text-danger">
											<X className="h-3 w-3" />
										</button>
									</span>
								))}
							</div>
						) : null}
						{editPreviewOpen ? (
							/* 预览后编辑（选项A）：编辑态默认渲染与查看态同源的 Markdown 预览，
							   内滚查看全文；点击/聚焦切到原生 textarea 真正编辑。 */
							<div
								className="xy-edit-preview xy-chat-text min-h-0 flex-1 resize-none cursor-text overflow-y-auto border-0 bg-transparent p-0 font-sans text-[15px] leading-relaxed text-ink outline-none"
								role="button"
								tabIndex={0}
								aria-label="点击开始编辑"
								onClick={openEditorFromPreview}
								onKeyDown={event => {
									if (event.key === 'Enter' || event.key === ' ') {
										event.preventDefault();
										openEditorFromPreview();
									}
								}}
							>
								<UserMarkdownText
									text={editingText}
									className="xy-chat-text min-w-0 font-sans text-[15px] leading-relaxed"
								/>
							</div>
						) : (
							<textarea
						ref={node => {
							if (editingTextareaRef) {
								editingTextareaRef.current = node;
							}
							if (node) {
								resizeEditingTextarea?.();
								/* 挂载首帧布局未定，下一帧再校一次高，避免长消息塌成一行 */
								requestAnimationFrame(() => resizeEditingTextarea?.());
							}
						}}
						value={editingText}
						onChange={event => {
							onEditTextChange?.(event.target.value);
							requestAnimationFrame(() => resizeEditingTextarea?.());
						}}
						onKeyDown={event => {
							if (event.key === 'Escape') {
								event.preventDefault();
								cancelEdit?.();
								return;
							}
							if (event.key === 'Enter' && !event.shiftKey) {
								event.preventDefault();
								submitEdit?.();
							}
						}}
						rows={1}
						className="xy-prompt-edit-ta xy-chat-text block min-h-0 w-full resize-none overflow-y-auto border-0 bg-transparent p-0 font-sans text-[15px] leading-relaxed text-ink outline-none"
						disabled={editingSubmitting || anyStreaming}
											aria-label="编辑历史消息"
						/>
						)}
					</>
					) : (
						<>
															{mediaRefs.length > 0 ? (
									<div className="mb-3 grid w-fit max-w-full grid-cols-[repeat(auto-fill,minmax(3.5rem,4.25rem))] gap-2">
										{mediaRefs.map((ref, index) => {
											const src = mediaUrl(ref);
											return src ? (
												<button
													key={`${ref}-${index}`}
													type="button"
													className="group relative aspect-square min-w-0 cursor-zoom-in overflow-hidden rounded-xl border border-line/40 bg-paper-deep/60 p-0 text-left"
													aria-label="查看已发送图片"
													onClick={event => {
														event.stopPropagation();
														setPreviewImage({src, alt: '已发送图片', title: '图片预览'});
													}}
												>
													<img src={src} alt="已发送图片" loading="lazy" decoding="async" className="h-full w-full object-cover" draggable={false} />
													<span className="pointer-events-none absolute right-1 bottom-1 flex h-6 w-6 items-center justify-center rounded-full bg-ink/60 text-paper opacity-0 shadow-sm transition-opacity duration-150 group-hover:opacity-100 group-focus-within:opacity-100">
														<ZoomIn className="h-3.5 w-3.5" strokeWidth={1.9} />
													</span>
												</button>
											) : null;
										})}
									</div>
								) : null}

								<PromptTextClamp>
								<UserMarkdownText
									text={body}
									className="xy-chat-text min-w-0 font-sans text-[15px] leading-relaxed"
								/>
							</PromptTextClamp>
						</>
					)}
							<ImageReaderDialog image={previewImage} onClose={() => setPreviewImage(null)} />
				{canEdit ? (

				<div
					className={cn('xy-editing-controls', controlsOpen && 'is-open')}
					aria-hidden={!editing}
				>
					<div className="xy-editing-controls-inner">
							<div className="mt-2 flex h-8 items-center justify-between gap-1">
								<input
									ref={editingFileInputRef}
									type="file"
									multiple
									accept="image/*,*/*"
									className="hidden"
									disabled={editingSubmitting || anyStreaming || editingUploading}
									onChange={event => {
										editingFilePickerOpenRef.current = false;
										onEditAttachmentPick?.(event.target.files);
								}}
								/>
								<button
									type="button"
																					data-xy-file-picker
																					disabled={editingSubmitting || anyStreaming || editingUploading}
																					onPointerDown={event => {
										editingFilePickerOpenRef.current = true;
										event.stopPropagation();
									}}
									onClick={() => editingFileInputRef?.current?.click()}
									className="xy-icon-btn flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-mute hover:bg-paper-deep hover:text-ink disabled:opacity-40"
									aria-label="添加文件"
									title="添加文件"
								>
									<Plus className="h-4 w-4" strokeWidth={2} />
								</button>
<div className="flex h-8 shrink-0 items-center gap-1">
									<div
									ref={editing ? editModelMenuRef : undefined}
									className="relative hidden sm:block"
								>
								<button
									type="button"
									aria-haspopup="listbox"
									aria-expanded={modelOpen}
									aria-controls={modelMenuId}
									disabled={anyStreaming || editingSubmitting || !editing}
									onClick={toggleModel}
									className={cn(
										'inline-flex h-7 max-w-[9.5rem] items-center gap-1 rounded-full px-2 font-mono text-[11px] leading-none text-mute',
										'hover:bg-ink/[0.06] hover:text-ink disabled:opacity-40',
										modelOpen && 'bg-ink/[0.08] text-ink',
									)}
									title="选择模型"
								>
									<span className="truncate">{model}</span>
									<ChevronDown
										className={cn(
											'h-3 w-3 shrink-0 opacity-50 transition-transform',
											modelOpen && 'rotate-180 opacity-70',
										)}
										aria-hidden
									/>
								</button>
								<div onClick={closeModel}>
									<ModelPicker
										open={editing && modelOpen}
										menuId={modelMenuId}
										portal
										anchorRef={editModelMenuRef}
										disabled={anyStreaming || editingSubmitting || !editing}
									/>
								</div>
							</div>
							<EditSendStopButton
								streaming={anyStreaming}
								canSend={(Boolean(editingText.trim()) || editingExistingMediaRefs.length > 0 || editingAttachments.length > 0) && !editingSubmitting && !editingUploading && editing}
								onSend={submitEdit ?? (() => undefined)}
								onStop={stopGeneration ?? (() => undefined)}
							/>
</div>
						</div>
					</div>
				</div>
			) : null}
		</div>
		);

		if (editing && (editPortalHost || lockEditFlow)) {
			const ph = Math.max(1, Math.round(editFlowHeight));
			const placeholder = (
				<div
					data-xy-prompt-chip
					data-xy-prompt-placeholder=""
					data-prompt-text={text}
					aria-hidden
					className="pointer-events-none invisible mx-auto w-full max-w-3xl shrink-0 rounded-2xl"
					style={{
						height: ph,
						maxHeight: ph,
						overflow: 'hidden',
					}}
				/>
			);
			if (editPortalHost) {
				return (
					<>
						{placeholder}
						{createPortal(chip, editPortalHost)}
					</>
				);
			}
			/* portal 尚未挂上时也绝不能在流内渲染可长高的编辑气泡 */
			return placeholder;
		}
		return chip;
}, promptBubblePropsAreEqual);

export function EditSendStopButton({
	streaming,
	canSend,
	onSend,
	onStop,
}: {
	streaming: boolean;
	canSend: boolean;
	onSend: () => void;
	onStop: () => void;
}) {
	return (
		<button
			type="button"
			onClick={streaming ? onStop : onSend}
			disabled={!streaming && !canSend}
			className={cn(
				'xy-press relative flex h-8 w-8 items-center justify-center rounded-full',
				streaming
					? 'bg-ink text-paper hover:bg-ink-soft'
					: canSend
						? 'bg-accent text-on-accent hover:bg-accent-hover'
						: 'cursor-not-allowed bg-paper-deep text-mute',
			)}
			title={streaming ? '停止生成' : '发送'}
			aria-label={streaming ? '停止生成' : '发送'}
		>
			<ArrowUp
				className={cn(
					'xy-send-stop-icon absolute h-4 w-4',
					streaming ? 'scale-90 opacity-0' : 'scale-100 opacity-100',
				)}
				strokeWidth={2.25}
				aria-hidden
			/>
			<Square
				className={cn(
					'xy-send-stop-icon absolute h-3 w-3 fill-current',
					streaming ? 'scale-100 opacity-100' : 'scale-90 opacity-0',
				)}
				aria-hidden
			/>
		</button>
	);
}
