/**
 * AUTO-GENERATED by dismantle-messagelist.cjs (spec api2: chatStream).
 * Blocks moved verbatim from components/MessageList.tsx. Behavior unchanged.
 */
import {
	useSettingsStore,
} from '@/stores/settingsStore';
import {allowsEmptyApiKey} from '@/lib/localTestGate';
import {
	useBrowserPreviewStore,
} from '@/stores/browserPreviewStore';
import {
	workspaceActiveTool,
} from '@/stores/storeRefs';
import {
	apiUrl,
} from '@/lib/apiBase';
import {
	STREAM_IDLE_TIMEOUT_MS,
	authHeaders,
	createStreamWatchdog,
	parseOpenAiSse,
	type ChatApiMessage,
	type ChatRequestOptions,
	type ChatStreamHandlers,
	type SseTermination,
} from './core';
import {TURN_CURSOR_KEY, formatStreamHttpError, getCachedModelContextLimit, rollbackApiErrorType} from '../api';

/** 浏览器预览面板打开且已加载 URL 时，供 LLM T_now 感知（省 token：无则不上报）。 */
function browserPreviewUrlForChat(): string | undefined {
	if (workspaceActiveTool() !== 'browser') {
		return undefined;
	}
	const url = useBrowserPreviewStore.getState().url?.trim();
	return url || undefined;
}

export async function streamChat(
	sessionId: string,
	input: string | ChatApiMessage[],
	handlers: ChatStreamHandlers,
	options?: ChatRequestOptions,
): Promise<void> {
	const s = useSettingsStore.getState();
	// 上下文窗口：优先厂商 /models 缓存（权威），账号里手动保存的值只在
	// 厂商未提供时兜底。
	const activeProfile = s.profiles.find(p => p.id === s.activeProfileId);
	const contextLimit =
		getCachedModelContextLimit(s.provider, s.resolvedBaseUrl(), s.model) ??
		(typeof activeProfile?.contextLimit === 'number' &&
		Number.isFinite(activeProfile.contextLimit) &&
		activeProfile.contextLimit > 0
			? activeProfile.contextLimit
			: undefined);
	// 最大输出 tokens：优先账号里保存的值；无则不发送（不限制）。
	const maxOutputTokens =
		typeof activeProfile?.maxOutputTokens === 'number' &&
		Number.isFinite(activeProfile.maxOutputTokens) &&
		activeProfile.maxOutputTokens > 0
			? activeProfile.maxOutputTokens
			: undefined;
	// 思考等级优先级：输入框手动选（options.reasoningEffort）> 模型默认等级 > 会话级。
	// 模型默认等级跌出该模型已登记支持集（历史遗留数据）→ 跳过该默认，避免发出
	// 模型不支持的 reasoning_effort。
	const activeModel =
		activeProfile?.models?.find(m => m.id === s.model);
	const modelDefaultEffort = activeModel?.defaultReasoningEffort || '';
	const modelDefaultSupported =
		!modelDefaultEffort ||
		!(activeModel?.reasoningLevels?.length) ||
		(activeModel?.reasoningLevels ?? []).includes(modelDefaultEffort);
	const defaultEffort =
		(modelDefaultSupported ? modelDefaultEffort : '') || s.reasoningEffort || '';
	const reasoningEffort =
		(options?.reasoningEffort?.trim() || defaultEffort) || undefined;
	const previewUrl = browserPreviewUrlForChat();
	// 空 Key 仅允许本地测试 provider（localTestGate，T25c）。
	if (!s.apiKey.trim() && !allowsEmptyApiKey(s.provider)) {
		handlers.onError('请先在设置中填写 API Key');
		return;
	}

	const messages: ChatApiMessage[] =
		typeof input === 'string'
			? input.trim() ? [{role: 'user', content: input.trim()}] : []
			: input.filter(m => m.content.trim().length > 0);
	const lastMessage = messages[messages.length - 1];
	if (!lastMessage || lastMessage.role !== 'user') {
		handlers.onError('消息为空');
		return;
	}



	let res: Response;
	const watchdog = createStreamWatchdog(handlers.signal);
	try {
		res = await fetch(apiUrl('/v1/chat/completions'), {
			method: 'POST',
			headers: {
				...authHeaders(),
				'X-Session-Id': sessionId,
			},
				body: JSON.stringify({
					model: s.model,
					stream: true,
					context_limit: contextLimit,
					max_tokens: maxOutputTokens,
					session_id: sessionId,
					provider: s.provider,
					base_url: s.resolvedBaseUrl(),
					thinking: s.thinking ?? 'disabled',
					reasoning_effort: reasoningEffort,
					// L1.2：USD 上限；空字符串 = 不限
					max_budget_usd: s.maxBudgetUsd ? Number(s.maxBudgetUsd) : undefined,
					permission_mode: s.permissionMode,
					// 输出精简：开启时后端在 T_now 尾部注入压缩铁律 + 模式段
					output_compact: s.outputCompact === true,
					output_mode: s.outputCompact ? s.outputMode : undefined,
					code_compact: s.codeCompact === true,
					code_mode: s.codeCompact ? s.codeMode : undefined,
					// 上一轮思考回顾：弱模型防重复思考兜底；默认关，子代理不继承。
					reasoning_tail: s.reasoningTail === true,
					...(previewUrl ? {browser_preview_url: previewUrl} : {}),
					searxng_url: s.searxngUrl?.trim() || undefined,
					agent_mode: options?.agentMode ?? 'agent',
					multi_agent: options?.multiAgent ?? false,
					// P1 mid-turn inbox：会话忙时排队（settle 后自动投递），
					// 而非 409 丢消息；side- 会话保持 409。
					...(sessionId.startsWith('side-')
						? {}
						: {queue_if_busy: true}),
					// 侧聊（side- 前缀会话）：复用同一回合链路，body.side 让后端
					// 收紧到只读工具白名单并跳过 workspace 内容注入；也不绑定
					// workspace（engine 回落 UI 启动目录，避免钉死到某个工程）。
					side: sessionId.startsWith('side-'),
					...(!sessionId.startsWith('side-') && options?.workspace?.trim()
						? {workspace: options.workspace.trim()}
						: {}),
						// 完整 transcript，供 BE 重启后 hydrate（#2）。
						messages,
						...(options?.mediaRefs?.length
							? {media_refs: options.mediaRefs}
							: {}),
					}),
			signal: watchdog.signal,
		});
	} catch (err) {
		watchdog.dispose();
		if (watchdog.timedOut()) {
			handlers.onError(`连接空闲超时：连续 ${STREAM_IDLE_TIMEOUT_MS / 1000} 秒未收到任何数据`);
			return;
		}
		handlers.onError(
			`无法连接后端 127.0.0.1:${import.meta.env.VITE_XEYO_HTTP_PORT || '8000'}（${err instanceof Error ? err.message : String(err)}）。请先运行：py -3.11 -m server`,
		);
		return;
	}

	if (!res.ok || res.status === 202) {
		watchdog.dispose();
		if (res.status === 202) {
			// P1：后端已把消息排进 FIFO（settle 后自动投递）——保留乐观气泡，
			// 标记 queued；不触发 onError（不撤回追加）。
			let q: {queue_id?: string; position?: number} = {};
			try {
				const j = (await res.json()) as {queue_id?: string; position?: number};
				q = j;
			} catch {
				/* 忽略 */
			}
			console.info('[inbox] 后端接受排队 (202)', {queue_id: q.queue_id, position: q.position});
			handlers.onQueued?.({queueId: q.queue_id ?? '', position: q.position ?? 0});
			return;
		}
		let payload: unknown = null;
		try {
			payload = await res.json();
		} catch {
			/* 忽略 */
		}
		// 所有 HTTP 状态拒绝都发生在 engine.submit 之前：后端从未写入用户
		// 消息，前端乐观追加必须撤回（session_busy 只是其中一种）。
		const busyKind =
			res.status === 409 && rollbackApiErrorType(payload) === 'session_busy'
				? {kind: 'session_busy' as const}
				: {kind: 'turn_not_started' as const};
		handlers.onError(formatStreamHttpError(payload, res.status), busyKind);
		return;
	}

	if (!res.body) {
		watchdog.dispose();
		handlers.onError('empty response body', {kind: 'connection_lost'});
		return;
	}

	try {
		const sse: SseTermination = {sawDone: false};
		for await (const ev of parseOpenAiSse(res.body, watchdog.touch, sse)) {
			const eid =
				'eventId' in ev && typeof (ev as {eventId?: number}).eventId === 'number'
					? (ev as {eventId?: number}).eventId
					: undefined;
			if (typeof eid === 'number') {
				rememberTurnCursor(sessionId, eid);
			}
			if (ev.kind === 'done') {
				break;
			}
			if (ev.kind === 'error') {
				handlers.onError(ev.message);
				return;
			}
			if (ev.kind === 'delta') {
				handlers.onDelta(ev.text);
				continue;
			}
			if (ev.kind === 'reasoning_delta') {
				handlers.onReasoningDelta?.(ev.text);
				continue;
			}
			if (ev.kind === 'llm_retry') {
				handlers.onLlmRetry?.({
					attempt: ev.attempt,
					nextRetryMs: ev.nextRetryMs,
					code: ev.code,
					message: ev.message,
					provider: ev.provider,
					model: ev.model,
				});
				continue;
			}
			if (ev.kind === 'llm_retry_started') {
				handlers.onLlmRetryStarted?.({attempt: ev.attempt, provider: ev.provider, model: ev.model});
				continue;
			}
			if (ev.kind === 'tool_call') {
				handlers.onToolCall?.({
					name: ev.name,
					input: ev.input,
					toolUseId: ev.toolUseId,
				});
				continue;
			}
			if (ev.kind === 'tool_result') {
				handlers.onToolResult?.({
					name: ev.name,
					output: ev.output,
					is_error: ev.is_error,
					todos: ev.todos,
					ui: ev.ui,
					toolUseId: ev.toolUseId,
				});
				continue;
			}
			if (ev.kind === 'tool_progress') {
				handlers.onToolProgress?.({
					name: ev.name,
					toolUseId: ev.toolUseId,
					message: ev.message,
					elapsedMs: ev.elapsedMs,
				});
				continue;
			}
				if (ev.kind === 'usage') {
					handlers.onUsage?.(ev);
					continue;
				}
				if (ev.kind === 'compression') {
					handlers.onCompression?.(ev);
					continue;
				}
				if (ev.kind === 'permission_pending') {
					handlers.onPermissionPending?.(ev);
					continue;
				}
				if (ev.kind === 'permission_resolved') {
					handlers.onPermissionResolved?.(ev);
					continue;
				}
				if (ev.kind === 'ask_user_pending') {
					handlers.onAskUserPending?.(ev);
					continue;
				}
				if (ev.kind === 'ask_user_resolved') {
					handlers.onAskUserResolved?.(ev);
					continue;
				}
				if (ev.kind === 'plan_pending') {
					handlers.onPlanPending?.(ev);
					continue;
				}
				if (ev.kind === 'plan_resolved') {
					handlers.onPlanResolved?.(ev);
					continue;
				}
			if (ev.kind === 'goal') {
				handlers.onGoal?.({
					goal: ev.goal,
					driver: ev.driver,
					sessionId: ev.sessionId,
					turnId: ev.turnId,
					eventId: ev.eventId,
				});
				continue;
			}
			if (ev.kind === 'jobs') {
				handlers.onJobs?.({
					jobs: ev.jobs,
					wake_budget_left: ev.wake_budget_left,
					sessionId: ev.sessionId,
					turnId: ev.turnId,
					eventId: ev.eventId,
				});
				continue;
			}
			if (ev.kind === 'task_state_changed') {
				handlers.onTaskState?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_task') {
				handlers.onMultiAgentTask?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_result') {
				handlers.onMultiAgentResult?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_progress') {
				handlers.onMultiAgentProgress?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_delta') {
				handlers.onMultiAgentDelta?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_status') {
				handlers.onMultiAgentStatus?.(ev);
				continue;
			}

		}
		if (!sse.sawDone && !handlers.signal?.aborted) {
			// 服务器提前关流/网络被掐 → 绝不能当正常结束（否则回复“静默停止”）。
			handlers.onError('连接中断：服务器提前关闭了流（未收到完成标记），请重试', {
				kind: 'connection_lost',
			});
			return;
		}
		handlers.onDone();
	} catch (err) {
		if (watchdog.timedOut()) {
			handlers.onError(`连接空闲超时：连续 ${STREAM_IDLE_TIMEOUT_MS / 1000} 秒未收到任何数据`, {
				kind: 'connection_lost',
			});
			return;
		}
		if ((err as Error).name === 'AbortError') {
			// 只有用户主动停止（外部 signal 已 abort）才静默收尾。
			if (handlers.signal?.aborted) {
				handlers.onDone();
				return;
			}
			handlers.onError('连接被意外中止，请重试', {kind: 'connection_lost'});
			return;
		}
		handlers.onError(err instanceof Error ? err.message : String(err), {
			kind: 'connection_lost',
		});
	} finally {
		watchdog.dispose();
	}
}


export type ServerSession = {
	id: string;
	title: string;
	createdAt: number;
	updatedAt: number;
};

/** 多 Agent：子 agent 元数据（卡片列表条目）。 */
export type SessionAgentMeta = {
	agentId: string;
	taskId: string;
	desc: string;
	status: string;
	resultPreview: string;
	hasTranscript: boolean;
	startedAt: number;
	readOnly?: boolean;
	scope?: string[];
	inboxCount?: number;
};

/** 列出会话跑过的子 agent（多 Agent 卡片 / 历史回放入口）。 */

export function rememberTurnCursor(sessionId: string, eventId: number): void {
	if (!sessionId || !Number.isFinite(eventId) || eventId < 0) return;
	try {
		sessionStorage.setItem(`${TURN_CURSOR_KEY}${sessionId}`, String(eventId));
	} catch {
		/* 忽略配额 */
	}
}

export function readTurnCursor(sessionId: string): number {
	try {
		const raw = sessionStorage.getItem(`${TURN_CURSOR_KEY}${sessionId}`);
		const n = Number(raw);
		return Number.isFinite(n) && n >= 0 ? n : 0;
	} catch {
		return 0;
	}
}

/** 刷新后重连：订阅后端 detached turn 的事件流（从 cursor 重放）。 */
export async function streamTurnEvents(
	sessionId: string,
	cursor: number,
	handlers: ChatStreamHandlers,
): Promise<void> {
	const watchdog = createStreamWatchdog(handlers.signal);
	let res: Response;
	try {
		const q = new URLSearchParams({cursor: String(Math.max(0, cursor))});
		res = await fetch(
			apiUrl(
				`/v1/sessions/${encodeURIComponent(sessionId)}/turns/current/events?${q}`,
			),
			{
				method: 'GET',
				headers: authHeaders(),
				signal: watchdog.signal,
			},
		);
	} catch (err) {
		watchdog.dispose();
		if (watchdog.timedOut()) {
			handlers.onError(
				`连接空闲超时：连续 ${STREAM_IDLE_TIMEOUT_MS / 1000} 秒未收到任何数据`,
				{kind: 'connection_lost'},
			);
			return;
		}
		if ((err as Error).name === 'AbortError') {
			if (handlers.signal?.aborted) {
				handlers.onDone();
				return;
			}
		}
		handlers.onError(
			err instanceof Error ? err.message : String(err),
			{kind: 'connection_lost'},
		);
		return;
	}
	if (!res.ok || !res.body) {
		watchdog.dispose();
		handlers.onError(
			!res.ok ? `reattach failed: HTTP ${res.status}` : 'empty response body',
			{kind: 'connection_lost'},
		);
		return;
	}
	try {
		const sse: SseTermination = {sawDone: false};
		for await (const ev of parseOpenAiSse(res.body, watchdog.touch, sse)) {
			const eid =
				'eventId' in ev && typeof (ev as {eventId?: number}).eventId === 'number'
					? (ev as {eventId?: number}).eventId
					: undefined;
			if (typeof eid === 'number') {
				rememberTurnCursor(sessionId, eid);
			}
			if (ev.kind === 'done') {
				break;
			}
			if (ev.kind === 'error') {
				handlers.onError(ev.message);
				return;
			}
			if (ev.kind === 'delta') {
				handlers.onDelta(ev.text);
				continue;
			}
			if (ev.kind === 'reasoning_delta') {
				handlers.onReasoningDelta?.(ev.text);
				continue;
			}
			if (ev.kind === 'llm_retry') {
				handlers.onLlmRetry?.({
					attempt: ev.attempt,
					nextRetryMs: ev.nextRetryMs,
					code: ev.code,
					message: ev.message,
					provider: ev.provider,
					model: ev.model,
				});
				continue;
			}
			if (ev.kind === 'llm_retry_started') {
				handlers.onLlmRetryStarted?.({attempt: ev.attempt, provider: ev.provider, model: ev.model});
				continue;
			}
			if (ev.kind === 'tool_call') {
				handlers.onToolCall?.({
					name: ev.name,
					input: ev.input,
					toolUseId: ev.toolUseId,
				});
				continue;
			}
			if (ev.kind === 'tool_result') {
				handlers.onToolResult?.({
					name: ev.name,
					output: ev.output,
					is_error: ev.is_error,
					todos: ev.todos,
					ui: ev.ui,
					toolUseId: ev.toolUseId,
				});
				continue;
			}
			if (ev.kind === 'tool_progress') {
				handlers.onToolProgress?.({
					name: ev.name,
					toolUseId: ev.toolUseId,
					message: ev.message,
					elapsedMs: ev.elapsedMs,
				});
				continue;
			}
			if (ev.kind === 'usage') {
				handlers.onUsage?.(ev);
				continue;
			}
			if (ev.kind === 'compression') {
				handlers.onCompression?.(ev);
				continue;
			}
			if (ev.kind === 'permission_pending') {
				handlers.onPermissionPending?.(ev);
				continue;
			}
			if (ev.kind === 'permission_resolved') {
				handlers.onPermissionResolved?.(ev);
				continue;
			}
			if (ev.kind === 'ask_user_pending') {
				handlers.onAskUserPending?.(ev);
				continue;
			}
			if (ev.kind === 'ask_user_resolved') {
				handlers.onAskUserResolved?.(ev);
				continue;
			}
			if (ev.kind === 'plan_pending') {
				handlers.onPlanPending?.(ev);
				continue;
			}
			if (ev.kind === 'plan_resolved') {
				handlers.onPlanResolved?.(ev);
				continue;
			}
			if (ev.kind === 'task_state_changed') {
				handlers.onTaskState?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_task') {
				handlers.onMultiAgentTask?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_result') {
				handlers.onMultiAgentResult?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_progress') {
				handlers.onMultiAgentProgress?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_delta') {
				handlers.onMultiAgentDelta?.(ev);
				continue;
			}
			if (ev.kind === 'multi_agent_status') {
				handlers.onMultiAgentStatus?.(ev);
				continue;
			}
		}
		// 与 streamChat 同样的收尾契约：没收到 [DONE] 说明连接被提前掐断
		// （后端重启/断网），不能把半截重放当正常结束——否则每次断连都会
		// 把重放文本追加成新的 assistant 气泡。
		if (!sse.sawDone && !handlers.signal?.aborted) {
			handlers.onError('连接中断：服务器提前关闭了流（未收到完成标记），请重试', {
				kind: 'connection_lost',
			});
			return;
		}
		handlers.onDone();
	} catch (err) {
		if (watchdog.timedOut()) {
			handlers.onError(
				`连接空闲超时：连续 ${STREAM_IDLE_TIMEOUT_MS / 1000} 秒未收到任何数据`,
				{kind: 'connection_lost'},
			);
			return;
		}
		if ((err as Error).name === 'AbortError') {
			if (handlers.signal?.aborted) {
				handlers.onDone();
				return;
			}
			handlers.onError('连接被意外中止，请重试', {kind: 'connection_lost'});
			return;
		}
		handlers.onError(err instanceof Error ? err.message : String(err), {
			kind: 'connection_lost',
		});
	} finally {
		watchdog.dispose();
	}
}

/** 确认或拒绝一个挂起的权限请求。 */
