/**
 * AUTO-GENERATED by dismantle-messagelist.cjs (spec api1: core).
 * 代码块自 components/MessageList.tsx 原样迁移，行为不变。
 */
import {
	useSettingsStore,
} from '@/stores/settingsStore';
import {
	apiUrl,
} from '@/lib/apiBase';
import {
	type AgentMode,
} from '../types';
import {allowsEmptyApiKey} from '@/lib/localTestGate';

export const MEDIA_REF_RE = /^xeyo-media:\/\/([0-9a-f]{64})$/i;

/** 将后端媒体引用转换为同一后端的只读预览地址。 */
export function mediaUrl(mediaRef: string): string {
	const match = MEDIA_REF_RE.exec((mediaRef || '').trim());
	return match ? apiUrl(`/v1/media/${match[1].toLowerCase()}`) : '';
}

export const REQUEST_TIMEOUT_MS = 20_000;
export const STREAM_IDLE_TIMEOUT_MS = 60_000;

export async function fetchWithTimeout(
	url: string,
	init?: RequestInit,
	timeoutMs = REQUEST_TIMEOUT_MS,
): Promise<Response> {
	const controller = new AbortController();
	const timer = setTimeout(() => controller.abort(), timeoutMs);
	try {
		return await fetch(url, {...init, signal: controller.signal});
	} catch (err) {
		if ((err as Error).name === 'AbortError') {
			throw new Error(
				`请求超时：${Math.round(timeoutMs / 1000)} 秒内未收到服务器响应`,
			);
		}
		throw err;
	} finally {
		clearTimeout(timer);
	}
}

export type StreamWatchdog = {
	signal: AbortSignal;
	touch: () => void;
	timedOut: () => boolean;
	dispose: () => void;
};

export function createStreamWatchdog(external: AbortSignal | undefined): StreamWatchdog {
	const controller = new AbortController();
	let idleTimedOut = false;
	let lastActiveAt = Date.now();
	const timer = setInterval(() => {
		if (Date.now() - lastActiveAt >= STREAM_IDLE_TIMEOUT_MS) {
			idleTimedOut = true;
			controller.abort();
		}
	}, 5000);
	const forwardAbort = () => controller.abort();
	external?.addEventListener('abort', forwardAbort);
	return {
		signal: controller.signal,
		touch: () => {
			lastActiveAt = Date.now();
		},
		timedOut: () => idleTimedOut,
		dispose: () => {
			clearInterval(timer);
			external?.removeEventListener('abort', forwardAbort);
		},
	};
}

export type EventIdentity = {
	version?: string;
	sessionId?: string;
	turnId?: string;
	eventId?: number;
	/** T13：request 级关联键（断线重连后同一次请求的事件仍可归组）。 */
	correlationId?: string;
};

export type ToolCallStreamEvent = {
	kind: 'tool_call';
	name: string;
	input: unknown;
	toolUseId?: string;
	/** T13：tool_call.begin 参数摘要 + 是否同批并行。 */
	inputSummary?: string;
	parallel?: boolean;
} & EventIdentity;

export type ToolResultStreamEvent = {
	kind: 'tool_result';
	name: string;
	output: string;
	is_error?: boolean;
	toolUseId?: string;
	/** 来自后端 SSE 旁路的结构化 TodoWrite 清单。 */
	todos?: unknown;
	/** XeyoUI 桌面旁路：open_preview / open_panel / send_to_session。 */
	ui?: unknown;
	/** T13：tool_call.end 元数据——执行耗时（ms）+ 是否 spill。 */
	durationMs?: number;
	spilled?: boolean;
} & EventIdentity;

export type ToolProgressStreamEvent = {
	kind: 'tool_progress';
	name: string;
	toolUseId?: string;
	message?: string;
	elapsedMs?: number;
} & EventIdentity;

export type UsageStreamEvent = {
	kind: 'usage';
	promptTokens: number;
	completionTokens: number;
	cacheHitTokens: number;
	cacheMissTokens: number;
	tokens: number;
	usedTokens: number;
	usd: number;
	usedUsd: number;
	cny: number;
	usedCny: number;
	costSource: 'api' | 'estimate' | 'unknown';
	usdLimit: number | null;
	contextTokens?: number;
	contextLimit?: number;
	/** 发送给模型的上下文构成（按内容分类的 token 数），用于画分段用量条。 */
	contextBreakdown?: {category: string; label: string; tokens: number}[];
	/** C2 压缩态（来自后端 WorkingSnapshot）。 */
	compactCursor?: number;
	lastAction?: string;
	c2SummaryChars?: number;
} & EventIdentity;

export type CompressionStreamEvent = {
	kind: 'compression';
	phase: 'start' | 'complete';
	source: 'automatic' | 'manual';
	contextTokens?: number;
	contextLimit?: number;
} & EventIdentity;

export type PermissionPendingStreamEvent = {
	kind: 'permission_pending';
	requestId: string;
	toolName: string;
	input: unknown;
	reason: string;
	prompt: string;
	path?: string | null;
	expiresAt?: number | null;
	/** 三选 peer ASK：deny / remind / allow；缺省为普通二元。 */
	choices?: string[];
	peerSummary?: string;
	/** T3：confirm（普通确认）/ choice（三选冲突）/ plan-review。 */
	intent?: string;
} & EventIdentity;

export type PermissionResolvedStreamEvent = {
	kind: 'permission_resolved';
	requestId: string;
	approved: boolean;
	actor: string;
	reason: string;
	resolvedAt?: number | null;
	choice?: string;
} & EventIdentity;

export type TaskStateStreamEvent = {
	kind: 'task_state_changed';
	status: string;
	currentTool?: string | null;
	interruptible: boolean;
	error?: string | null;
} & EventIdentity;

export type AskUserPendingStreamEvent = {
	kind: 'ask_user_pending';
	requestId: string;
	question: string;
	options: string[];
	default?: string | null;
	expiresAt?: number | null;
} & EventIdentity;

export type AskUserResolvedStreamEvent = {
	kind: 'ask_user_resolved';
	requestId: string;
	answer?: string;
	actor?: string;
	timeout?: boolean;
	resolvedAt?: number | null;
} & EventIdentity;

export type PlanPendingStreamEvent = {
	kind: 'plan_pending';
	requestId: string;
	sessionId?: string;
	turnId?: string;
	plan: string;
	expiresAt?: number | null;
} & EventIdentity;

export type PlanResolvedStreamEvent = {
	kind: 'plan_resolved';
	requestId: string;
	approved: boolean;
	actor: string;
	reason: string;
	resolvedAt?: number | null;
} & EventIdentity;

/**
 * 41 号：goal 投影帧（whole-value，turn 起点推送）。
 * payload = Goal.to_dict() + driver 快照；见 lib/api/goals.ts 的归一化。
 */
export type GoalStreamEvent = {
	kind: 'goal';
	goal: unknown;
	driver: unknown;
} & EventIdentity;

/**
 * 42 号：后台任务 whole-value 快照帧（turn 起点播种；owner turn 存活期内
 * 结算变化由 GET 轮询补齐）。payload = JobRecord.to_dict() 列表。
 */
export type JobsStreamEvent = {
	kind: 'jobs';
	jobs: unknown[];
	wake_budget_left?: number;
} & EventIdentity;

/** 多 Agent：单个子任务卡片的运行时视图。 */
export type MultiAgentTaskView = {
	uid: string;
	taskId: string;
	agentId: string;
	desc: string;
	status: 'pending' | 'running' | 'done' | 'failed';
	reason?: string;
	result?: string;
	/** 空 scope = 只读工人（无 Write/Edit）。 */
	readOnly?: boolean;
	/** 允许写入的路径前缀（有值时非只读）。 */
	scope?: string[];
	/** 子 Agent 实际改过的路径（主会话 Changes 汇总用）。 */
	filesTouched?: string[];
	/** 产生该批次的后端 SSE turn_id（仅实时流可得；历史批为空）。 */
	turnId?: string;
	/**
	 * 批次出现时刻（本地毫秒；历史批合并时取 meta.startedAt）。
	 * 渲染期据此把卡片锚定到「此前最近一条用户消息」所在轮。
	 */
	batchAt?: number;
	/** P2：该 agent 的 follow-up 收件箱数（列表 API 带来；>0 卡片角标）。 */
	inboxCount?: number;
};

export type MultiAgentTaskStreamEvent = {
	kind: 'multi_agent_task';
	uid: string;
	taskId: string;
	agentId: string;
	desc: string;
	status: string;
	readOnly?: boolean;
	scope?: string[];
} & EventIdentity;

export type MultiAgentResultStreamEvent = {
	kind: 'multi_agent_result';
	tasks: MultiAgentTaskView[];
} & EventIdentity;

/** 多 Agent：单个子任务的实时进度（开始/落定即时推送，不等全批）。 */
export type MultiAgentProgressStreamEvent = {
	kind: 'multi_agent_progress';
	uid: string;
	taskId: string;
	agentId: string;
	status: 'pending' | 'running' | 'done' | 'failed';
	reason?: string;
	result?: string;
} & EventIdentity;

/** 多 Agent：子 agent 输出的 token 级文本增量（同一 SSE 流内按 agent 有序）。 */
export type MultiAgentDeltaStreamEvent = {
	kind: 'multi_agent_delta';
	uid: string;
	taskId: string;
	agentId: string;
	text: string;
} & EventIdentity;

/** 多 Agent：批阶段状态（分解中 / 运行中），用于 Composer 状态行。 */
export type MultiAgentStatusStreamEvent = {
	kind: 'multi_agent_status';
	phase: string;
	text: string;
} & EventIdentity;

export type ReasoningStreamEvent = {
	kind: 'reasoning_delta';
	text: string;
} & EventIdentity;

/** 44 号：LLM 重试调度决策帧（非 surface，不进 transcript）。 */
export type LlmRetryStreamEvent = {
	kind: 'llm_retry';
	attempt: number;
	nextRetryMs: number;
	code: string;
	message?: string;
	provider?: string;
	model?: string;
} & EventIdentity;

/** 44 号：LLM 重试实际开始帧（非 surface）。 */
export type LlmRetryStartedStreamEvent = {
	kind: 'llm_retry_started';
	attempt: number;
	provider?: string;
	model?: string;
} & EventIdentity;

export type ChatStreamHandlers = {
	onDelta: (text: string) => void;
	onReasoningDelta?: (text: string) => void;
	onToolCall?: (ev: Omit<ToolCallStreamEvent, 'kind'>) => void;
	onToolResult?: (ev: Omit<ToolResultStreamEvent, 'kind'>) => void;
	onToolProgress?: (ev: Omit<ToolProgressStreamEvent, 'kind'>) => void;
	onUsage?: (ev: UsageStreamEvent) => void;
	onCompression?: (ev: Omit<CompressionStreamEvent, 'kind'>) => void;
	onPermissionPending?: (ev: PermissionPendingStreamEvent) => void;
	onPermissionResolved?: (ev: PermissionResolvedStreamEvent) => void;
	onAskUserPending?: (ev: AskUserPendingStreamEvent) => void;
	onAskUserResolved?: (ev: AskUserResolvedStreamEvent) => void;
	onPlanPending?: (ev: PlanPendingStreamEvent) => void;
	onPlanResolved?: (ev: PlanResolvedStreamEvent) => void;
	/** 41 号：goal 投影帧（whole-value：goal + driver 快照，turn 起点推送）。 */
	onGoal?: (ev: Omit<GoalStreamEvent, 'kind'>) => void;
	/** 42 号：后台任务 whole-value 快照帧（空集 = 删除键）。 */
	onJobs?: (ev: Omit<JobsStreamEvent, 'kind'>) => void;
	onTaskState?: (ev: TaskStateStreamEvent) => void;
	/** 多 Agent：子任务开始（FE 展示「正在运行」卡片）。 */
	onMultiAgentTask?: (ev: Omit<MultiAgentTaskStreamEvent, 'kind'>) => void;
	/** 多 Agent：批量结果汇总（FE 卡片落定 done/failed）。 */
	onMultiAgentResult?: (ev: Omit<MultiAgentResultStreamEvent, 'kind'>) => void;
	/** 多 Agent：单任务实时进度（每子 agent 开始/结束即推）。 */
	onMultiAgentProgress?: (ev: Omit<MultiAgentProgressStreamEvent, 'kind'>) => void;
	/** 多 Agent：子 agent 输出的 token 级增量（实时逐字回放）。 */
	onMultiAgentDelta?: (ev: Omit<MultiAgentDeltaStreamEvent, 'kind'>) => void;
	onMultiAgentStatus?: (ev: Omit<MultiAgentStatusStreamEvent, 'kind'>) => void;
	/** 44 号：LLM 重试调度决策（前端可渲染倒计时，P0 可只为留痕）。 */
	onLlmRetry?: (ev: Omit<LlmRetryStreamEvent, 'kind'>) => void;
	/** 44 号：LLM 重试实际开始。 */
	onLlmRetryStarted?: (ev: Omit<LlmRetryStartedStreamEvent, 'kind'>) => void;
	onDone: () => void;
	/** P1 mid-turn inbox：会话忙时后端排队并返回 202（乐观气泡保留并标记 queued）。 */
	onQueued?: (ev: {queueId: string; position: number}) => void;
	/**
	 * opts.kind 区分回合是否已启动：
	 * - 'session_busy'：409 租约占用，回合未启动；
	 * - 'turn_not_started'：其他 HTTP 状态拒绝（4xx/5xx），回合同样未启动，
	 *   后端从未收到用户消息——本地乐观追加必须撤回。
	 * 两者都不应触发 interrupt（没有可中断的回合）。
	 * - 'connection_lost'：T29 断流（空闲超时/服务器提前关流/读错误/意外中止）
	 *   ——回合仍活着，调用方必须走 reattach 恢复管线，绝不自动 interrupt。
	 * 无 opts = 流中引擎错误帧（用户消息已落服务端），照旧保留。
	 */
	onError: (
		message: string,
		opts?: {kind?: 'session_busy' | 'turn_not_started' | 'connection_lost'},
	) => void;
	signal?: AbortSignal;
};

export type ParsedSse =
	| {kind: 'delta'; text: string}
	| ReasoningStreamEvent
	| ToolCallStreamEvent
	| ToolResultStreamEvent
	| ToolProgressStreamEvent
	| UsageStreamEvent
	| CompressionStreamEvent
	| PermissionPendingStreamEvent
	| PermissionResolvedStreamEvent
	| AskUserPendingStreamEvent
	| AskUserResolvedStreamEvent
	| PlanPendingStreamEvent
	| PlanResolvedStreamEvent
	| GoalStreamEvent
	| JobsStreamEvent
	| TaskStateStreamEvent
	| MultiAgentTaskStreamEvent
	| MultiAgentResultStreamEvent
	| MultiAgentProgressStreamEvent
	| MultiAgentDeltaStreamEvent
	| MultiAgentStatusStreamEvent
	| LlmRetryStreamEvent
	| LlmRetryStartedStreamEvent
	| {kind: 'done'}
	| {kind: 'error'; message: string};

/** parseOpenAiSse 的终止状态：流是正常收到 [DONE]，还是被提前掐断。 */
export type SseTermination = {sawDone: boolean};

export function readIdentity(xy: {
	schema_version?: unknown;
	session_id?: unknown;
	turn_id?: unknown;
	event_id?: unknown;
	correlation_id?: unknown;
}): EventIdentity {
	return {
		version: typeof xy.schema_version === 'string' ? xy.schema_version : undefined,
		sessionId: typeof xy.session_id === 'string' ? xy.session_id : undefined,
		turnId: typeof xy.turn_id === 'string' ? xy.turn_id : undefined,
		eventId: Number.isFinite(Number(xy.event_id)) ? Number(xy.event_id) : undefined,
		correlationId:
			typeof xy.correlation_id === 'string' ? xy.correlation_id : undefined,
	};
}

export function authHeaders(): HeadersInit {
	const s = useSettingsStore.getState();
	const headers: Record<string, string> = {
		'Content-Type': 'application/json',
		'X-Provider': s.provider,
		'X-Base-Url': s.resolvedBaseUrl(),
	};
	// 空 Key 仅允许本地测试 provider（localTestGate，T25c）。
	if (s.apiKey.trim() || allowsEmptyApiKey(s.provider)) {
		headers.Authorization = `Bearer ${s.apiKey.trim() || 'local'}`;
	}
	return headers;
}

export function formatErrorDetail(payload: unknown, status: number): string {
	if (!payload || typeof payload !== 'object') {
		if (status === 500) {
			return `HTTP 500：后端异常或未启动（请确认已运行 py -3.11 -m server，端口 ${import.meta.env.VITE_XEYO_HTTP_PORT || '8000'}）`;
		}
		return `HTTP ${status}`;
	}
	const obj = payload as {
		detail?: unknown;
		error?: unknown;
		message?: unknown;
	};
	// 优先 Task4 统一格式：{error:{message,type}}
	const errObj = obj.error;
	if (errObj && typeof errObj === 'object' && !Array.isArray(errObj)) {
		const row = errObj as {message?: unknown; type?: unknown};
		if (typeof row.message === 'string' && row.message.trim()) {
			return row.message;
		}
	}
	const detail = obj.detail ?? obj.error ?? obj.message;
	if (typeof detail === 'string') {
		return detail;
	}
	if (Array.isArray(detail)) {
		return detail
			.map(item => {
				if (item && typeof item === 'object' && 'msg' in item) {
					const row = item as {loc?: unknown[]; msg?: string};
					const loc = Array.isArray(row.loc) ? row.loc.join('.') : '';
					return loc ? `${loc}: ${row.msg}` : String(row.msg);
				}
				return JSON.stringify(item);
			})
			.join('; ');
	}
	if (detail && typeof detail === 'object') {
		const row = detail as {message?: unknown};
		if (typeof row.message === 'string') {
			return row.message;
		}
		return JSON.stringify(detail);
	}
	return `HTTP ${status}`;
}

export function parseSseBlock(part: string): ParsedSse | null {
	const dataLines = part
		.split('\n')
		.map(l => l.trim())
		.filter(l => l.startsWith('data:'))
		.map(l => l.slice('data:'.length).trim());
	if (dataLines.length === 0) {
		return null;
	}
	const data = dataLines.join('\n');
	if (!data) {
		return null;
	}
	if (data === '[DONE]') {
		return {kind: 'done'};
	}
	try {
		const obj = JSON.parse(data) as {
			choices?: {delta?: {content?: string}}[];
			error?: {message?: string};
			xy?: {
				type?: string;
				name?: string;
				input?: unknown;
				output?: unknown;
				is_error?: boolean;
				todos?: unknown;
				goal?: unknown;
				driver?: unknown;
				ui?: unknown;
				prompt_tokens?: number;
				completion_tokens?: number;
				cache_hit_tokens?: number;
				cache_miss_tokens?: number;
					tokens?: number;
					used_tokens?: number;
					usd?: number;
					used_usd?: number;
					cny?: number;
					used_cny?: number;
					cost_source?: string;
					usd_limit?: number | null;
					context_tokens?: number;
					context_limit?: number;
					context_breakdown?: unknown;
					source?: string;
					schema_version?: string;
					session_id?: string;
					turn_id?: string;
					event_id?: number;
					request_id?: string;
					tool_name?: string;
					reason?: string;
					prompt?: string;
					path?: string | null;
					expires_at?: number | null;
					approved?: boolean;
					actor?: string;
					resolved_at?: number | null;
					task_status?: string;
					current_tool?: string | null;
					interruptible?: boolean;
					error?: string | null;
					question?: string;
					options?: unknown;
					default?: string | null;
					answer?: string;
					timeout?: boolean;
					plan?: string;
					uid?: string;
					task_id?: string;
					agent_id?: string;
					desc?: string;
					status?: string;
					result?: string;
					text?: unknown;
					tasks?: unknown;
					/** 后端可能下发更多字段（如 compact_cursor/last_action/scope/read_only/choice 等），放宽为 unknown 以便按守卫收窄 */
					[key: string]: unknown;
				};
		};
		if (obj.error?.message) {
			return {kind: 'error', message: obj.error.message};
		}
		const xy = obj.xy;
		if (xy && typeof xy === 'object') {
				if (xy.type === 'reasoning_delta') {
					const text = typeof xy.text === 'string' ? xy.text : '';
					if (!text) {
						return null;
					}
					return {
						kind: 'reasoning_delta',
						text,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'usage') {
					return {
						kind: 'usage',
						promptTokens: Number(xy.prompt_tokens ?? 0),
						completionTokens: Number(xy.completion_tokens ?? 0),
						cacheHitTokens: Number(xy.cache_hit_tokens ?? 0),
						cacheMissTokens: Number(xy.cache_miss_tokens ?? 0),
						tokens: Number(xy.tokens ?? 0),
						usedTokens: Number(xy.used_tokens ?? xy.tokens ?? 0),
						usd: Number(xy.usd ?? 0),
						usedUsd: Number(xy.used_usd ?? 0),
						cny: Number(xy.cny ?? 0),
						usedCny: Number(xy.used_cny ?? 0),
						costSource: xy.cost_source === 'api' ? 'api' : 'estimate',
						usdLimit: xy.usd_limit == null ? null : Number(xy.usd_limit),
						contextTokens: Number.isFinite(Number(xy.context_tokens)) ? Number(xy.context_tokens) : undefined,
						contextLimit: Number.isFinite(Number(xy.context_limit)) ? Number(xy.context_limit) : undefined,
						contextBreakdown: Array.isArray(xy.context_breakdown)
							? (xy.context_breakdown as unknown[])
									.map((row: unknown) => {
										const it = row as {category?: unknown; label?: unknown; tokens?: unknown};
										return {
											category: String(it.category ?? ''),
											label: String(it.label ?? ''),
											tokens: Number.isFinite(Number(it.tokens)) ? Number(it.tokens) : 0,
										};
									})
									.filter((it: {category: string; tokens: number}) => it.category && it.tokens > 0)
							: undefined,
						compactCursor: Number.isFinite(Number(xy.compact_cursor))
							? Math.max(0, Number(xy.compact_cursor))
							: undefined,
						lastAction: typeof xy.last_action === 'string' ? xy.last_action : undefined,
						c2SummaryChars: Number.isFinite(Number(xy.c2_summary_chars))
							? Math.max(0, Number(xy.c2_summary_chars))
							: undefined,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'llm_retry') {
					return {
						kind: 'llm_retry',
						attempt: Number(xy.attempt ?? 0),
						nextRetryMs: Number(xy.next_retry_ms ?? 0),
						code: String(xy.code ?? ''),
						message: typeof xy.message === 'string' ? xy.message : undefined,
						provider: typeof xy.provider === 'string' ? xy.provider : undefined,
						model: typeof xy.model === 'string' ? xy.model : undefined,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'llm_retry_started') {
					return {
						kind: 'llm_retry_started',
						attempt: Number(xy.attempt ?? 0),
						provider: typeof xy.provider === 'string' ? xy.provider : undefined,
						model: typeof xy.model === 'string' ? xy.model : undefined,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'context_compression_start' || xy.type === 'context_compression_complete') {
					return {
						kind: 'compression',
						phase: xy.type.endsWith('start') ? 'start' : 'complete',
						source: xy.source === 'manual' ? 'manual' : 'automatic',
						contextTokens: Number.isFinite(Number(xy.context_tokens)) ? Number(xy.context_tokens) : undefined,
						contextLimit: Number.isFinite(Number(xy.context_limit)) ? Number(xy.context_limit) : undefined,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'permission_pending') {
					return {
						kind: 'permission_pending',
						requestId: String(xy.request_id ?? ''),
						toolName: String(xy.tool_name ?? ''),
						input: xy.input ?? {},
						reason: String(xy.reason ?? ''),
						prompt: String(xy.prompt ?? ''),
						path: xy.path == null ? undefined : String(xy.path),
						expiresAt: Number.isFinite(Number(xy.expires_at)) ? Number(xy.expires_at) : undefined,
						choices: Array.isArray(xy.choices) ? xy.choices.map(String) : undefined,
						peerSummary: xy.peer_summary == null ? undefined : String(xy.peer_summary),
						...readIdentity(xy),
					};
				}
				if (xy.type === 'permission_resolved') {
					return {
						kind: 'permission_resolved',
						requestId: String(xy.request_id ?? ''),
						approved: Boolean(xy.approved),
						actor: String(xy.actor ?? ''),
						reason: String(xy.reason ?? ''),
						resolvedAt: Number.isFinite(Number(xy.resolved_at)) ? Number(xy.resolved_at) : undefined,
						choice: xy.choice == null ? undefined : String(xy.choice),
						...readIdentity(xy),
					};
				}
				if (xy.type === 'ask_user_pending') {
					return {
						kind: 'ask_user_pending',
						requestId: String(xy.request_id ?? ''),
						question: String(xy.question ?? ''),
						options: Array.isArray(xy.options) ? xy.options.map(String) : [],
						default: xy.default == null ? undefined : String(xy.default),
						expiresAt: Number.isFinite(Number(xy.expires_at)) ? Number(xy.expires_at) : undefined,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'ask_user_resolved') {
					return {
						kind: 'ask_user_resolved',
						requestId: String(xy.request_id ?? ''),
						answer: xy.answer == null ? undefined : String(xy.answer),
						actor: String(xy.actor ?? ''),
						timeout: Boolean(xy.timeout),
						resolvedAt: Number.isFinite(Number(xy.resolved_at)) ? Number(xy.resolved_at) : undefined,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'plan_pending') {
					return {
						kind: 'plan_pending',
						requestId: String(xy.request_id ?? ''),
						sessionId: typeof xy.session_id === 'string' ? xy.session_id : undefined,
						turnId: typeof xy.turn_id === 'string' ? xy.turn_id : undefined,
						plan: String(xy.plan ?? ''),
						expiresAt: Number.isFinite(Number(xy.expires_at)) ? Number(xy.expires_at) : undefined,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'plan_resolved') {
					return {
						kind: 'plan_resolved',
						requestId: String(xy.request_id ?? ''),
						approved: Boolean(xy.approved),
						actor: String(xy.actor ?? ''),
						reason: String(xy.reason ?? ''),
						resolvedAt: Number.isFinite(Number(xy.resolved_at)) ? Number(xy.resolved_at) : undefined,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'goal') {
					// 41 号：whole-value goal + driver 快照，交给归一化后落 store。
					return {
						kind: 'goal',
						goal: xy.goal ?? null,
						driver: xy.driver ?? null,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'jobs') {
					// 42 号：whole-value jobs 快照（空集 = 删除键）。
					return {
						kind: 'jobs',
						jobs: Array.isArray(xy.jobs) ? xy.jobs : [],
						wake_budget_left: Number.isFinite(Number(xy.wake_budget_left))
							? Number(xy.wake_budget_left)
							: undefined,
						...readIdentity(xy),
					};
				}
				if (xy.type === 'task_state_changed') {
					return {
						kind: 'task_state_changed',
						status: String(xy.task_status ?? ''),
						currentTool: xy.current_tool == null ? undefined : String(xy.current_tool),
						interruptible: xy.interruptible !== false,
						error: xy.error == null ? undefined : String(xy.error),
						...readIdentity(xy),
					};
				}
				if (xy.type === 'multi_agent_task') {
				const scope = Array.isArray(xy.scope)
					? xy.scope.map(String).filter(Boolean)
					: undefined;
				const readOnly =
					typeof xy.read_only === 'boolean'
						? xy.read_only
						: scope
							? scope.length === 0
							: undefined;
				return {
					kind: 'multi_agent_task',
					uid: String(xy.uid ?? xy.task_id ?? ''),
					taskId: String(xy.task_id ?? ''),
					agentId: String(xy.agent_id ?? ''),
					desc: String(xy.desc ?? ''),
					status: String(xy.status ?? 'running'),
					...(readOnly !== undefined ? {readOnly} : {}),
					...(scope ? {scope} : {}),
					...readIdentity(xy),
				};
			}
			if (xy.type === 'multi_agent_result') {
				const rawTasks = Array.isArray(xy.tasks) ? xy.tasks : [];
				return {
					kind: 'multi_agent_result',
					tasks: rawTasks
						.map((item): MultiAgentTaskView | null => {
							if (!item || typeof item !== 'object') {
								return null;
							}
							const row = item as {
								id?: unknown; uid?: unknown; agent_id?: unknown;
								desc?: unknown; status?: unknown; reason?: unknown; result?: unknown;
								files_touched?: unknown;
							};
							const taskId = String(row.id ?? '');
							const uid = String(row.uid ?? '') || taskId;
							if (!uid) {
								return null;
							}
							const st = String(row.status ?? 'failed');
							const filesTouched = Array.isArray(row.files_touched)
								? row.files_touched.map(String).filter(Boolean)
								: undefined;
							return {
								uid,
								taskId,
								agentId: String(row.agent_id ?? ''),
								desc: String(row.desc ?? ''),
								status: st === 'done' ? 'done' : 'failed',
								reason: typeof row.reason === 'string' ? row.reason : undefined,
								result: typeof row.result === 'string' ? row.result : undefined,
								...(filesTouched?.length ? {filesTouched} : {}),
							};
						})
						.filter((t): t is MultiAgentTaskView => t !== null),
					...readIdentity(xy),
				};
			}
			if (xy.type === 'multi_agent_progress') {
				const st = String(xy.status ?? 'running');
				return {
					kind: 'multi_agent_progress',
					uid: String(xy.uid ?? xy.task_id ?? ''),
					taskId: String(xy.task_id ?? ''),
					agentId: String(xy.agent_id ?? ''),
					status: (st === 'done' || st === 'failed' || st === 'pending' ? st : 'running'),
					reason: typeof xy.reason === 'string' && xy.reason ? xy.reason : undefined,
					result: typeof xy.result === 'string' && xy.result ? xy.result : undefined,
					...readIdentity(xy),
				};
			}
			if (xy.type === 'multi_agent_delta') {
				const text = typeof xy.text === 'string' ? xy.text : '';
				if (!text) {
					return null;
				}
				return {
					kind: 'multi_agent_delta',
					uid: String(xy.uid ?? xy.task_id ?? ''),
					taskId: String(xy.task_id ?? ''),
					agentId: String(xy.agent_id ?? ''),
					text,
					...readIdentity(xy),
				};
			}
			if (xy.type === 'multi_agent_status') {
				const text = typeof xy.text === 'string' ? xy.text.trim() : '';
				if (!text) {
					return null;
				}
				return {
					kind: 'multi_agent_status',
					phase: String(xy.phase ?? ''),
					text,
					...readIdentity(xy),
				};
			}
			if (typeof xy.name === 'string') {
			if (xy.type === 'tool_call') {
				return {
					kind: 'tool_call',
					name: xy.name,
					input: xy.input ?? {},
					toolUseId:
						typeof xy.tool_use_id === 'string' ? xy.tool_use_id : undefined,
					inputSummary:
						typeof xy.input_summary === 'string' ? xy.input_summary : undefined,
					parallel: Boolean(xy.parallel),
					...readIdentity(xy),
				};
			}
			if (xy.type === 'tool_result') {
				return {
					kind: 'tool_result',
					name: xy.name,
					output: String(xy.output ?? ''),
					is_error: Boolean(xy.is_error),
					toolUseId:
						typeof xy.tool_use_id === 'string' ? xy.tool_use_id : undefined,
					...(xy.todos !== undefined ? {todos: xy.todos} : {}),
					...(xy.ui !== undefined ? {ui: xy.ui} : {}),
					durationMs: Number.isFinite(Number(xy.duration_ms))
						? Number(xy.duration_ms)
						: undefined,
					spilled: Boolean(xy.spilled),
					...readIdentity(xy),
				};
			}
			if (xy.type === 'tool_progress') {
				return {
					kind: 'tool_progress',
					name: xy.name,
					toolUseId:
						typeof xy.tool_use_id === 'string' ? xy.tool_use_id : undefined,
					message: typeof xy.message === 'string' ? xy.message : undefined,
					elapsedMs:
						typeof xy.elapsed_ms === 'number' ? xy.elapsed_ms : undefined,
					...readIdentity(xy),
				};
			}
			}
		}
		const content = obj.choices?.[0]?.delta?.content;
		if (typeof content === 'string' && content.length > 0) {
			return {kind: 'delta', text: content};
		}
		return null;
	} catch (err) {
		if (err instanceof SyntaxError) {
			return null;
		}
		throw err;
	}
}

export async function* parseOpenAiSse(
	body: ReadableStream<Uint8Array>,
	onActivity?: () => void,
	termination?: SseTermination,
): AsyncGenerator<ParsedSse> {
	const reader = body.getReader();
	const decoder = new TextDecoder('utf-8');
	let buffer = '';

	while (true) {
		const {done, value} = await reader.read();
		if (done) {
			break;
		}
		onActivity?.();
		buffer += decoder.decode(value, {stream: true});
		const parts = buffer.split('\n\n');
		buffer = parts.pop() ?? '';
		for (const part of parts) {
			const ev = parseSseBlock(part);
			if (!ev) {
				continue;
			}
			if (ev.kind === 'done' && termination) {
				termination.sawDone = true;
			}
			yield ev;
			if (ev.kind === 'done' || ev.kind === 'error') {
				return;
			}
		}
	}
	// 刷新尾部帧（部分代理会省略最后的空行）。
	buffer += decoder.decode();
	if (buffer.trim()) {
		const ev = parseSseBlock(buffer);
		if (ev) {
			if (ev.kind === 'done' && termination) {
				termination.sawDone = true;
			}
			yield ev;
		}
	}
}

/** 发送至 `/v1/chat/completions` 的 OpenAI 风格对话轮次。 */
export type ChatApiMessage = {
	role: 'user' | 'assistant' | 'system';
	content: string;
	/** 与本地 ChatMessage.id 对齐，供 rewind journal / transcript 关联。 */
	id?: string;
	/** 仅 user 消息可携带已上传的本机媒体引用。 */
	media_refs?: string[];
};

export type ChatRequestOptions = {
	mediaRefs?: string[];
	agentMode?: AgentMode;
	/** 多 Agent：前端 "+" 菜单开启（Multi-Agent）。True 时 BE 若收到 tasks 走批量调度。 */
	multiAgent?: boolean;
	/** 该 session 钉死的工作区根。 */
	workspace?: string;
	/** 会话级思考等级覆盖（输入框手动选）；优先级最高，其次模型默认等级，再次会话级。 */
	reasoningEffort?: string;
};
