/**
 * AUTO-GENERATED by dismantle-messagelist.cjs (spec api5: memory).
 * Blocks moved verbatim from components/MessageList.tsx. Behavior unchanged.
 */
import {
	apiUrl,
} from '@/lib/apiBase';
import {
	fetchWithTimeout,
} from './core';
import {MemoryNoteRow} from '../api';

export async function fetchMemoryNotes(
	scope = '',
	limit = 40,
): Promise<MemoryNoteRow[]> {
	try {
		const q = new URLSearchParams();
		if (scope) q.set('scope', scope);
		q.set('limit', String(limit));
		const res = await fetchWithTimeout(apiUrl(`/v1/memory/notes?${q}`), {
			cache: 'no-store',
		});
		if (!res.ok) return [];
		const data = (await res.json()) as {notes?: MemoryNoteRow[]};
		return Array.isArray(data.notes) ? data.notes : [];
	} catch {
		return [];
	}
}

/** 手动 /compact（不进模型循环）。 */
export async function requestManualCompact(
	sessionId: string,
): Promise<{ok: boolean; compact_cursor: number; c2_summary_chars?: number; reason?: string}> {
	const sid = sessionId.trim();
	if (!sid) return {ok: false, compact_cursor: 0, reason: 'no_session'};
	const res = await fetchWithTimeout(apiUrl('/v1/memory/compact'), {
		method: 'POST',
		headers: {'Content-Type': 'application/json'},
		body: JSON.stringify({session_id: sid}),
	});
	if (!res.ok) {
		return {ok: false, compact_cursor: 0, reason: `http_${res.status}`};
	}
	return (await res.json()) as {
		ok: boolean;
		compact_cursor: number;
		c2_summary_chars?: number;
		reason?: string;
	};
}

/** 把 finalized Thought 块同步到服务端 transcript（ui_thought 行）。 */
export async function syncUiThoughtsToServer(
	sessionId: string,
	thoughts: Array<{
		id: string;
		text: string;
		thoughtMs?: number;
		createdAt: number;
	}>,
): Promise<number> {
	if (!sessionId || thoughts.length === 0) {
		return 0;
	}
	try {
		const res = await fetchWithTimeout(
			apiUrl(`/v1/sessions/${encodeURIComponent(sessionId)}/ui-thoughts`),
			{
				method: 'POST',
				headers: {'Content-Type': 'application/json'},
				body: JSON.stringify({
					thoughts: thoughts.map(t => ({
						id: t.id,
						text: t.text,
						thought_ms: t.thoughtMs,
						ts: t.createdAt / 1000,
					})),
				}),
			},
		);
		if (!res.ok) {
			return 0;
		}
		const payload = (await res.json()) as {written?: number};
		return payload.written ?? 0;
	} catch {
		return 0;
	}
}
