/**
 * AUTO-GENERATED by dismantle-messagelist.cjs (spec api6: permissions).
 * Blocks moved verbatim from components/MessageList.tsx. Behavior unchanged.
 */
import {
	apiUrl,
} from '@/lib/apiBase';
import {
	fetchWithTimeout,
} from './core';

export async function resolvePermission(
	requestId: string,
	approved: boolean,
	actor = 'desktop',
	outcome?: 'allow' | 'deny' | 'remind',
	remember = false,
): Promise<boolean> {
	try {
		const res = await fetchWithTimeout(apiUrl('/v1/permission/resolve'), {
			method: 'POST',
			headers: {'Content-Type': 'application/json'},
			body: JSON.stringify({
				request_id: requestId,
				approved,
				actor,
				remember,
				...(outcome ? {outcome} : {}),
			}),
		});
		if (!res.ok) return false;
		const payload = (await res.json()) as {ok?: boolean};
		return payload.ok === true;
	} catch {
		return false;
	}
}

/** T10：always-allow 授权（"don't ask again"）条目。 */
export type PermissionGrantInfo = {
	grant_id: string;
	tool_name: string;
	fingerprint: string;
	scope: string;
	created_at: number;
	expires_at: number | null;
	actor: string;
};

/** T10：列出 always-allow 授权（空 scope = 全部）。 */
export async function listPermissionGrants(
	scope?: string,
): Promise<PermissionGrantInfo[]> {
	try {
		const q = scope ? `?scope=${encodeURIComponent(scope)}` : '';
		const res = await fetchWithTimeout(apiUrl(`/v1/permissions/grants${q}`));
		if (!res.ok) return [];
		const payload = (await res.json()) as {grants?: PermissionGrantInfo[]};
		return Array.isArray(payload.grants) ? payload.grants : [];
	} catch {
		return [];
	}
}

/** T10：撤销一个 always-allow 授权。 */
export async function revokePermissionGrant(grantId: string): Promise<boolean> {
	try {
		const res = await fetchWithTimeout(
			apiUrl(`/v1/permissions/grants/${encodeURIComponent(grantId)}`),
			{method: 'DELETE'},
		);
		if (!res.ok) return false;
		const payload = (await res.json()) as {ok?: boolean};
		return payload.ok === true;
	} catch {
		return false;
	}
}

/** 提交对一个挂起提问（AskUserQuestion）的作答。 */
export async function resolveAsk(
	requestId: string,
	answer: string,
	actor = 'desktop',
): Promise<boolean> {
	try {
		const res = await fetchWithTimeout(apiUrl('/v1/ask/resolve'), {
			method: 'POST',
			headers: {'Content-Type': 'application/json'},
			body: JSON.stringify({request_id: requestId, answer, actor}),
		});
		if (!res.ok) return false;
		const payload = (await res.json()) as {ok?: boolean};
		return payload.ok === true;
	} catch {
		return false;
	}
}

/** 批准或拒绝一个 Plan 模式下挂起的实现计划。 */
export async function resolvePlan(
	requestId: string,
	approved: boolean,
	actor = 'desktop',
): Promise<boolean> {
	try {
		const res = await fetchWithTimeout(
			apiUrl(`/v1/plan/${encodeURIComponent(requestId)}/approve`),
			{
				method: 'POST',
				headers: {'Content-Type': 'application/json'},
				body: JSON.stringify({approved, actor}),
			},
		);
		if (!res.ok) return false;
		const payload = (await res.json()) as {ok?: boolean};
		return payload.ok === true;
	} catch {
		return false;
	}
}

/** 删除后端 session transcript 与内存 engine；成功返回 true。 */
