/**
 * AUTO-GENERATED by dismantle-messagelist.cjs (spec api7: uploads).
 * 代码块自 components/MessageList.tsx 原样迁移，行为不变。
 */
import {
	apiUrl,
} from '@/lib/apiBase';
import {
	formatErrorDetail,
} from './core';
import {MediaUploadResult} from '../api';

export async function uploadMedia(file: File): Promise<MediaUploadResult> {
	const form = new FormData();
	form.append('file', file);
	let res: Response;
	try {
		res = await fetch(apiUrl('/v1/media/upload'), {method: 'POST', body: form});
	} catch (err) {
		throw new Error(
			`无法连接图片上传接口（${err instanceof Error ? err.message : String(err)}）`,
		);
	}
	if (!res.ok) {
		let payload: unknown = null;
		try {
			payload = await res.json();
		} catch {
			/* 忽略 */
		}
		throw new Error(formatErrorDetail(payload, res.status));
	}
	return (await res.json()) as MediaUploadResult;
}

export async function uploadFile(file: File): Promise<{
	filename: string;
	text: string;
}> {
	const form = new FormData();
	form.append('file', file);
	let res: Response;
	try {
		res = await fetch(apiUrl('/v1/files'), {method: 'POST', body: form});
	} catch (err) {
		throw new Error(
			`无法连接后端上传接口（${err instanceof Error ? err.message : String(err)}）`,
		);
	}
	if (!res.ok) {
		let payload: unknown = null;
		try {
			payload = await res.json();
		} catch {
			/* 忽略 */
		}
		throw new Error(formatErrorDetail(payload, res.status));
	}
	return (await res.json()) as {filename: string; text: string};
}
